### ISSUE TITLE
pdoResources and createdon

### ISSUE THREAD

**Issue by pepebe** [modx-pro/pdoTools#105]
I get weird results if I try to modify a date inside a tpl. 

```
<!-- $latest_news -->
                [[pdoResources?
                    &parents=`11`
                    &tpl=`widgets-home_latest-news_tpl`
                    &includeContent=`1`
                ]]
```

```
<!-- $widgets-home_latest-news_tpl -->
                <p class="day">[[+createdon:strtotime:date=`%e`]]</p>
                <p class="monthyear">[[+createdon:strtotime:date=`%b. %Y`]]</p>
```

If I have a couple of resources, the first one will display giberish. The following ones don't return anything at all.

The same code works flawlessly with [[getResources]]. Did I miss something in the documentation?

Cheers,

pepebe

**Comment by bezumkin** [comment]
Why you using strtotime?

MODX stores all dates of resources as timestamps, and pdoResources returns raw values.

```
<!-- $widgets-home_latest-news_tpl -->
<p class="day">[[+createdon:date=`%e`]]</p>
<p class="monthyear">[[+createdon:date=`%b. %Y`]]</p>
```
