### ISSUE TITLE
Bug in pdoFetch?

### ISSUE THREAD

**Issue by BobRay** [modx-pro/pdoTools#108]
Line 408 of the pdoFetch file:

if (!empty($this->config['sortbyTV']) && !array_key_exists($this->config['sortbyTV'], $tmp['sortby'])) {

Shouldn't that be:

if (!empty($this->config['sortbyTV']) && !array_key_exists($this->config['sortbyTV'], $tmp)) {

I don't think $tmp['sortby'] is ever set, and this line throws an error (array_key_exists() -- arg 2 is not an array).

See this: http://forums.modx.com/thread/96356/what-does-this-error-from-pdoresources-mean

**Comment by bezumkin** [comment]
You right, it is just a typo.

I fixed it and added parameters for TVs in pdoResources.
