### ISSUE TITLE
pdoResources, limit & permissions

### ISSUE THREAD

**Issue by pitangaweb** [modx-pro/pdoTools#109]
When calling pdoResources with limit = `3`, if one of these 3 resources has restricted access permissions, it outputs only 2 resources.

It should instead output 3 resources that do not have restricted access permissions, not 2.

This is an issue when used with pagination. We end up with empty pages.

**Comment by bezumkin** [comment]
It is impossible due to checking of permissions **after** fetching data from DB.

There is no solution to check permissions before fetching, so this issue persists in all MODX components, as I know. You can check how getResources work, for example.
