### ISSUE TITLE
Не учитываются источники файлов при вызове TV

### ISSUE THREAD

**Issue by maxpoletaev** [modx-pro/pdoTools#11]
Значения файловых TV, вне зависимости от выбранного источника файлов, выводятся относительно корня.

К примеру, есть у нас источник Uploads, смотрящий в http://sitename/uploads/, если мы зальем туда картинку, укажем ее в TV и попробуем вызвать это TV внутри шаблона pdoResources, то путь к картинке будет выведен как http://sitename/image.jpg а не http://sitename/uploads/image.jpg.

MODX Revolution 2.2.10-pl (advanced)
pdoTools 1.8.0-rc5

**Comment by bezumkin** [comment]
В свойствах ТВ должен быть указан источник файлов, а у сниппета параметр &prepareTVs=1

Только что проверил - все работает. Если не так - прошу продемонстрировать на  http://modx-test.com

**Comment by maxpoletaev** [comment]
http://s4003.modx-test.com/index.php?id=2
s4003; 7Pu86GO5oamt

**Comment by bezumkin** [comment]
Параметры getResources, конечно, учитываются, но нужно читать и параметры pdoResources.

А у него ТВ указываются вот так:

<pre>&includeTVs=`catalog.item.image`</pre>

И тогда все работает.

**Comment by maxpoletaev** [comment]
Стыдно за свою невнимательность. Спасибо.

**Comment by bezumkin** [comment]
Не за что! Я со своей стороны тоже исправлю этот момент, чтобы учитывался.
