### ISSUE TITLE
Need to exclude just children, not both parent and children

### ISSUE THREAD

**Issue by SnowCreative** [modx-pro/pdoTools#110]
We need a way to exclude the children of a resource but still show that parent in the menu. I don't see any setting that will do this.

**Comment by bezumkin** [comment]
You need to specify an ids of excluded resources with a dash:

```
[[!pdoMenu?
    &parents=`0`
    &resources=`-15,-20`
    &showLog=`1`
]]
```

And, of course, you can use **hidemenu** property of resources.

**Comment by SnowCreative** [comment]
That will exclude resources and their children. I want to exclude the children of a resource, but NOT the resource itself. I don't want to use hidemenu because menus in a different area of the site need to display the children.

**Comment by SnowCreative** [comment]
I know I could write a script to create the list of child resources to omit, and that's what I've done with Wayfinder menus before. It would just be nicer to have a setting to so that (like "-15" would omit a parent resource and its children and "15-" would omit the children but NOT the parent resource, or something like that).
