### ISSUE TITLE
TVs with JSON content broken in pdoResources?

### ISSUE THREAD

**Issue by pepebe** [modx-pro/pdoTools#114]
I've stumbled over a strange problem.

I'm pulling a JSON string from a Google Maps TV into a pdoResources call.

**body_js chunk**

```
        $(function() {
            new Maplace({
            locations: [
                [[pdoResources?
                    &parents=`19`
                    &tpl=`maplace-locations_tpl`
                    &includeTVs=`GoogleMapsTV,URL`
                    &prepareTVs=`1`
                    &outputSeparator=`,`
                ]]
            ]
            ,controls_on_map: false
            }).Load();
        });
```

**maplace-locations_tpl**

```
{
    [[+tv.GoogleMapsTV:JSONtoChunk=`maplace-locations-geo_tpl`]]
    title: '[[+pagetitle]]',
    html: '<h3>[[+pagetitle]]</h3><p><a href="[[+tv.URL]]">[[+tv.URL]]</a></p>',
    icon: 'http://maps.google.com/mapfiles/markerA.png',
    animation: google.maps.Animation.DROP
}
```

As it turned out I didn't get any return value from JSONtoChunk.

To make sure that the snippet wasn't not the root of the problem, I removed it and simply added the TV

**maplace-locations_tpl (alternative version)**

```
{
    json: [[+tv.GoogleMapsTV]]
    title: '[[+pagetitle]]',
    html: '<h3>[[+pagetitle]]</h3><p><a href="[[+tv.URL]]">[[+tv.URL]]</a></p>',
    icon: 'http://maps.google.com/mapfiles/markerA.png',
    animation: google.maps.Animation.DROP
}
```

to the &tpl chunk. Again [[+tv.GoogleMapsTV]] returned nothing.

I double-checked for typos and also checked if [[*GoogleMapsTV]] returns values on templates it is used.

**Example of the expected JSON string:**

```
{"street":" Ausserrotte","housenumber":"37","zipcode":"9963","city":"St. Jakob","state":"","country":"Austria","latitude":"46.9114708","longitude":"12.35188960000005"}
```

Is it possible that pdoResources has a problem with json content inside placeholders and tvs?

Regards,

pepebe

**Comment by pepebe** [comment]
Update: I've filled the JSON string above into a simple Text TV and it had the same effect. No content is returned. If I remove the JSON string from the TV and add something else, it is displayed.

**Comment by bezumkin** [comment]
Try to specify

```
&decodeJSON=`0`
```

**Comment by pepebe** [comment]
That hit the spot. Thanks!

I can't find this parameter in the docs and it is also not part of the drag and drop property modal. Is this an experimental feature, how is decodeJSON used?

**Comment by bezumkin** [comment]
It is part of basic pdoTools functionality.

You can [find it here](http://docs.modx.pro/components/pdotools/general-settings).

**Comment by pepebe** [comment]
Quote: Разбирает поля типа JSON вместо вывода в виде строки

Google translate says this parameter "Parses the JSON field type instead of displaying a line". This sounds interesting but I don't have a clue what it does. Can you give a use case?

**Comment by bezumkin** [comment]
It is for proper work with JSON fields of tables. For example, field **extended** in modResource.

MODX store it as text in table and pdoTools get it as is. So, if we want to use [[+extended.placeholder]] as in getResources, pdoTools must [parse JSON string to array](https://github.com/bezumkin/pdoTools/blob/c39bc9481b9adab25076d1a3651de9de4674d75f/core/components/pdotools/model/pdotools/pdotools.class.php#L672-L681).

**Comment by pepebe** [comment]
Ah, got it. Thank you!

Case closed!
