### ISSUE TITLE
pdoMenu classes placeholder output problem

### ISSUE THREAD

**Issue by akimsullec** [modx-pro/pdoTools#117]
Проблема с выводом плейсхолдера [[+classes]]
если в темплейт записать вывод вот так:
class="bg-[[+id]]" [[+classes]], то плейсхолдер не отрендерится  на странице - class="bg-[[+id]]"
если записать вот  так:
class="bg-[[+id]] [[+classes]]", то отрендерится вот так: class="bg-22  class=" first""

**Comment by bezumkin** [comment]
Для таких случаев есть [[[+classnames]]](https://github.com/bezumkin/pdoTools/blob/7850ab526f67fd7bfcac8043348dc0584ef6c5a2/core/components/pdotools/model/pdotools/pdomenu.class.php#L102-L104)
