### ISSUE TITLE
(ERROR @ /index.php) Could not load class: pdofetch from pdotools.pdofetch.

### ISSUE THREAD

**Issue by osabate** [modx-pro/pdoTools#120]
I'm getting a bunch of these errors on the ModX error log since I upgraded pdoTools to the latest version (1.11.1)

**Comment by bezumkin** [comment]
It can be if you don`t have write permissions for the /core/model/ path and installation script could not copy [those files](https://github.com/bezumkin/pdoTools/tree/master/core/model/modx/pdotools).
