### ISSUE TITLE
Возможность указать свой класс для обработки в pdoPage

### ISSUE THREAD

**Issue by faitno** [modx-pro/pdoTools#122]
Было бы замечательно иметь возможность расширять класс [pdoPage](https://github.com/bezumkin/pdoTools/blob/master/core/components/pdotools/model/pdotools/pdopage.class.php#L3) своим классом, к примеру мне нужно изменить логику работы метода [makePageLink](https://github.com/bezumkin/pdoTools/blob/master/core/components/pdotools/model/pdotools/pdopage.class.php#L154) для этого можно запросто расширить класс pdoPage до, к примеру pdoPageCustom и было бы замечательно передать сниппету pdoPage свой класс, к примеру так:

```
[[!pdoPage?
    &classPHP=`pdoPageCustom`
    &parents=`0`
    &ajaxMode=`button`
    &limit=`5`
]]
```

**Comment by bezumkin** [comment]
Теперь можно использовать свои классы для pdoPage и pdoMenu [примерно так](https://github.com/bezumkin/pdoTools/issues/27#issuecomment-31602321).

**Comment by faitno** [comment]
Круто. пример с выбором чанка на основе текущего языка)
