### ISSUE TITLE
Ошибка с PdoMenu и категориями в Minishop 2

### ISSUE THREAD

**Issue by Sqaier** [modx-pro/pdoTools#123]
### pdotools-2.0.1-pl

При попытке вывести меню с родительским ресурсом  - категория товаров. Внутри него так же содержатся категории товаров и параметром &displayStart=`1`, ничего не выводится. Если убрать данный параметр, то всё работает
### Пример:

> [[pdoMenu?
>     &parents=`34`
>     &level=`1`
>     &outerClass=`col-lg-2 col-sm-2 col-md-2 unstyled`
>     &displayStart=`1`
>     ]]

**Comment by bezumkin** [comment]
Не могу повторить
[![](https://file.modx.pro/files/f/6/f/f6fc72ba4e0624d28cefc26305d9fce5s.jpg)](https://file.modx.pro/files/f/6/f/f6fc72ba4e0624d28cefc26305d9fce5.png)  [![](https://file.modx.pro/files/c/f/3/cf3ae0c070b2b167f589ddc0dd5ed367s.jpg)](https://file.modx.pro/files/c/f/3/cf3ae0c070b2b167f589ddc0dd5ed367.png)

**Comment by justenj** [comment]
Василий, данный баг действительно существует. 
Он возникает когда включена опция displayStart=`1` и родитель ресурса,  указанного в "parent", не проходит проверку этим методом https://github.com/bezumkin/pdoTools/blob/master/core/components/pdotools/model/pdotools/pdomenu.class.php#L353

**Пример:**
Имеем дерево: 
1. Дедушка

1.1. Отец

1.1.1. Ребенок 1

1.1.2. Ребенок 2

1.1.3. Ребенок 3

В качестве "parents" указываем ресурс "Отец" плюс опция "displayStart=`1`". И если "Дедушка" распубликован, или скрыт из меню, сниппет отработает некорректно.
