### ISSUE TITLE
Strange behaviour of pdoPage with using parameter tvFilters - no paginate

### ISSUE THREAD

**Issue by alroniks** [modx-pro/pdoTools#124]
I need use tvFilter for create simple search by params. Example here http://massagist.by/wiki/
pdoPage called on page once. If I remove tvFilters - pagination works. If use - alway first page (302 redirect when I attempt go to another page).

Example of my code:

```
[[!pdoPage:default=`Поиск не дал результатов. Попробуйте изменить параметры поиска.`?
        &element=`pdoResources`
        &parents=`[[*id]]`
        &tpl=`news.row`
        &includeTVs=`wiki_region,wiki_type,wiki_tool`
        &tvFilters=`[[!tvfilters?]]`
        &sortby=`pagetitle`
        &sortdir=`asc`
        &showLog=`0`
        &limit=`10`
        &maxLimit=`10`
        &ajax=`0`
    ]]

    <div class="page-list">
        [[!+page.nav]]
    </div>
```

Snippet `[[tvfilters]]` just generate actual json for using in this parameter. Nothing extraordinary.

**Comment by bezumkin** [comment]
Включай параметр &showLog и смотри, какой получается запрос.

Редирект на первую страницу происходит, если нет результатов.

**Comment by alroniks** [comment]
Уже. Total показывает правильное количество ресурсов. Если параметры в $_GET не указаны, то tvFilter вообще пустой, за это отвечает сниппет, который генерирует json. Т.е. сбрасывает даже когда просто указать tvFilters

**Comment by bezumkin** [comment]
Если $_GET действительно пустой, то там нет и номера страницы - будет редирект.

Или редирект происходит всегда при пустом tvFilters? Вообще, попробуй посмотреть, где именно происходит редирект, при каком условии в [сниппете](https://github.com/bezumkin/pdoTools/blob/master/core/components/pdotools/elements/snippets/snippet.pdopage.php). Просто поищи по вызову redirectToFirst.

**Comment by alroniks** [comment]
Разобрался. Косяк был мой, хотя и хитрый довольно. В showLog все ок было по фильтрам, а на деле перехватывался параметр page в снипете tvfilter и оригинальный page всегда равнялся 1.

**Comment by bezumkin** [comment]
Хорошо, что разобрались.
