### ISSUE TITLE
sortby Не понимает русский

### ISSUE THREAD

**Issue by Skippidar** [modx-pro/pdoTools#126]
Если сортировать по доп.полю 'test' - то всё нормально выводится, если же по полю 'Цена' - не выводится ничего. То есть почему-то TV с названием на кириллице дает сбой.
Поля созданы, всё есть.

Вызов:
[[pdoResources? 
  &tpl=`@CODE: [[+tv.Цена со скидкой]]` 
  &parents=`[[+id]]` 
  &includeTVs=`Цена со скидкой` 
  &where=`{"template:=":6}`  
  &sortby=`Цена со скидкой` 
  &limit=`1` 
  &sortdir=`ASC`
]]

**Comment by bezumkin** [comment]
На русском, да еще и с пробелам? Толково придумано!

Включайте showLog и учите MySQL это воспринимать.

**Comment by Skippidar** [comment]
А, все, дело не в кириллице, а в пробелах, добавление кавычек в запрос помогло

**Comment by bezumkin** [comment]
У TV же есть поле **caption** - это типа название, туда можно писать что угодно, оно показывается менеджерам в админке.

A **name** - это ключ TV, лучше его на русском не писать, могут быть еще проблемы.

**Comment by Skippidar** [comment]
Да это я в курсе, вот только когда я начинал разбираться с modx я ничего не знал, никаких "правил", всё по примерам разбирался, ну и методом тыка. Попробовал на русском с пробелами - работает, да и так было проще разбираться в структуре. Поэтому раньше писал на русском и с пробелами.

Форкнул ветку, поправил на своей, а как сделать pull-request на эту ветку - не знаю.
