### ISSUE TITLE
добавляет лишний /

### ISSUE THREAD

**Issue by Nik-ADA** [modx-pro/pdoTools#128]
при использование pdoResources для картинок добавляет в начало лишний /

**Comment by bezumkin** [comment]
Отличное описание проблемы, прям сразу всё понятно.

**Comment by Nik-ADA** [comment]
вызов снипита
[[!pdoPage? &tpl=`staff_tpl` &parents=`[[*id]]` &pageLimit=`6` &includeTVs=`left_image` ]]

left_image - типа Tv image с установленным Источником файлов (отличным от Filesystem)
Настройки Mediasource:
basePath - [[++assets_path]]images/
basePathRelative: 0
baseUrl: [[++assets_url]]images/
baseUrlRelative: 1

итог TV left_image выводится примерно так //assets/images/doc/1853.jpg

место того что бы вывести так /assets/images/doc/1853.jpg

**Comment by bezumkin** [comment]
```
baseUrl: [[++assets_url]]images/
baseUrlRelative: 1
```

Это 2 взаимоисключающих опции.

Или baseUrl: images/ и baseUrlRelative: 1
или [[++assets_url]]images/ и baseUrlRelative: 0

**Comment by Nik-ADA** [comment]
но при вызове getResources
картинка отображается нормально

**Comment by bezumkin** [comment]
Ну так и пользуйтесь getResources, не вижу проблемы.

**Comment by Nik-ADA** [comment]
я ожидал данный ответ.
