### ISSUE TITLE
mFilter и двойные кавычки в TV

### ISSUE THREAD

**Issue by alexburma** [modx-pro/pdoTools#129]
Столкнулся со следующей проблемой: есть текстовый TV, который используется в фильтре. Если в значении фильтра будет использоваться текст с кавычкой, то фильтр ничего не выведет.
Как решить вопрос?

**Comment by bezumkin** [comment]
Не использовать в поле name кавычки, потому что это имя используется в SQL запросах.

Кавычки можно писать в поле caption, которое есть у всех ТВ.

**Comment by bezumkin** [comment]
Исправлено в версии 1.3.5-pl. Можно обновляться через https://modstore.pro.
