### ISSUE TITLE
&tplInnerRow property & custom snippet placeholder problem

### ISSUE THREAD

**Issue by mtalvenheimo** [modx-pro/pdoTools#130]
Hi, 
I have a custom snippet call in chunk defined by &tplInnerRow -property:

`<li class="[[dropdowntoggleCheck? &resource=`[[+id]]`]]">...`

For some reason &resource parameter won't pass [[+id]] placeholder for the snippet?

With &tpl -property same snippet/placeholder works?

**Comment by mtalvenheimo** [comment]
Actually placeholder will pass to snippet. 
Snippet:

```
$page = $modx->getObject('modResource' , &resource);
$getid = $page->get('id'); //<- get() method is causing error. 
return $getid;
```

For some reason snippet isn't working on &tplInnerRow -property and works on &tpl -property.

Maybe thi is not related to pdoTools/pdoMenu?

**Comment by bezumkin** [comment]
> Maybe thi is not related to pdoTools/pdoMenu?

Of course it is not related.

```
if ($page = $modx->getObject('modResource' , $resource)) {
    return $page->get('id');
}
```

Not &resource but **$**resource.
