### ISSUE TITLE
[[+pubslishedon]] in pdoResources tpl displays odd dates or nothing at all

### ISSUE THREAD

**Issue by frogabog** [modx-pro/pdoTools#133]
I tested this out on two different sites, so I'm fairly sure it's exclusive to pdoResources at this point.

On a current site being redeveloped, using pdoResources and [[+publishedon]] results in really odd output.  See http://forums.modx.com/thread/97720/getresources-publishedon#dis-post-528499

Initially, I did get output, but it resulted in a year that none of us will ever see:
Thursday, July 17, 5913

After seeing that for a couple reloads, the page was reloaded again and nothing was returned at all.  The weird date never came back.

On another site, it worked fine but that site is using getResources/getPage.  To test this, I changed the call from getResources to pdoResources.  Which made the results disappear.  Also tested with no getPage and just pdoResources.  pdoResources again lost the date.  Did not get weird dates this time at all, just no output.

**Comment by bezumkin** [comment]
MODX stores all dates of resources as timestamps, and pdoResources returns raw integer values without format.

pdoResources **is not** getResources and do not must work as any as any another snippet.

See also https://github.com/bezumkin/pdoTools/issues/105
