### ISSUE TITLE
Расхождение умолчательного значения sortdir у pdoResource в документации и по факту

### ISSUE THREAD

**Issue by PatchRanger** [modx-pro/pdoTools#134]
Умолчательное значение параметра `sortdir` сниппета `pdoResources` по факту имеет значение `DESC`, а [в документации](http://docs.modx.pro/components/pdotools/snippets/pdoresources#Параметры-выборки-ресурсов) указано `ASC`.
Завожу заявку сюда, а не в документацию, потому что мне кажется, что правильным умолчанием является сортировка по возрастанию (`ASC`).
Кстати, эта же проблема вскользь озвучивалась в уже закрытой заявке на другую тему: #73 (см. последний абзац изначального сообщения).

**Comment by bezumkin** [comment]
Нет, правильной является вывод документов по дате рубликации в порядке убывания. Новые сверху.

Тем более, если изменить **параметр по умолчанию**, то очень многие пользователи сниппета удивлятся при обновлении.
