### ISSUE TITLE
Не отрабатывает &tplCategoryFolder

### ISSUE THREAD

**Issue by largod** [modx-pro/pdoTools#137]
Сниппет pdoMenu. При условии isfolder = 1 (то есть ресурс - категория), не подтягивает шаблон для категорий.

**Comment by bezumkin** [comment]
[Смотрим исходник](https://github.com/bezumkin/pdoTools/blob/b20b63288e4b5feaebcb1b6ef88b9c60e64854b0/core/components/pdotools/model/pdotools/pdomenu.class.php#L288) - у категории должны быть потомки и или пустой шаблон, или указание category в link_attributes.

Эта логика взята из Wayfinder.

**Comment by largod** [comment]
У категории есть потомки, в том то и дело... И все включены, и не спрятаны.

12 августа 2015 г., 21:19 пользователь Vasily Naumkin <
notifications@github.com> написал:

**Comment by bezumkin** [comment]
А еще должен быть:
- или пустой шаблон (поле template = 0)
- или указание **category** в поле **link_attributes**

**Comment by largod** [comment]
Проставлял. Но, фишка вот в чем, если органичить выборку &level=`1`, тогда
вообще никак не работает. А если включить бОльшую глубину, то работает. Но
не охота выбирать столько значений...

12 августа 2015 г., 21:37 пользователь Vasily Naumkin <
notifications@github.com> написал:

**Comment by bezumkin** [comment]
Ну так если level низкий, то и потомков у ресурса как бы нет.
