### ISSUE TITLE
 Unexpected character in input: '\' Error on line 474

### ISSUE THREAD

**Issue by mdxthemes** [modx-pro/pdoTools#138]
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /path/core/components/pdotools/model/pdotools/pdotools.class.php on line 474

Parse error: syntax error, unexpected T_STRING in /path/core/components/pdotools/model/pdotools/pdotools.class.php on line 474

Removing the \ fixes the error. 

if ($tpl instanceof Fenom\Render) {

**Comment by bezumkin** [comment]
pdoTools 2.0 requires at least PHP 5.3
