### ISSUE TITLE
pdoMenu

### ISSUE THREAD

**Issue by ershov-ilya** [modx-pro/pdoTools#139]
Параметр **checkPermissions** перестаёт работать при глубине поиска больше 1
Вызов:

```
[[!pdoMenu?
&parents=`16`
&level=`1`
&checkPermissions=`list`
]]
```

Работает **OK**

Вызов &level=**2**:

```
[[!pdoMenu?
&parents=`16`
&level=`2`
&checkPermissions=`list`
]]
```

**Пустой результат**

Баг наблюдал в версиях:
pdoTools: 2.0.5 - 2.1.3
MODX: 2.3.5 - 2.4.0

**Comment by bezumkin** [comment]
Проверяю на modx.pro, раздел пользователей:

```
[[!pdoMenu?
    &parents=`30`
    &showHidden=`1`
    &level=`1`
    &checkPermissions=`list`
]]
```

[![](https://file.modx.pro/files/4/8/2/482025fbf2678b989007f5a0618f5ce4s.jpg)](https://file.modx.pro/files/4/8/2/482025fbf2678b989007f5a0618f5ce4.png)

```
[[!pdoMenu?
    &parents=`30`
    &showHidden=`1`
    &level=`2`
    &checkPermissions=`list`
]]
```

[![](https://file.modx.pro/files/1/2/e/12ee8f15b602db64705ca5d1ad7f9affs.jpg)](https://file.modx.pro/files/1/2/e/12ee8f15b602db64705ca5d1ad7f9aff.png)

Мне кажется, если бы в сниппете был действительно **такой** глюк, это бы давно заметили. Так что, скорее всего, это твоя индивидуальная проблема.

Например, какой-то ресурс закрыт для пользователя и не проходит проверку на **list**, из-за чего ломается вывод дерева.

**Comment by ershov-ilya** [comment]
Не знаю... у меня точно не работает. Система почти нулевая:
- 3 группы пользователей
- 3 группы ресурсов, с правами только для своей группы
- 3 дерева ресурсов, каждое внесено в свою группу ресурсов, причём в группу ресурсов внесены не только корневые, но и дочерние ресурсы...
  Результат - описанный выше глюк

**Comment by bezumkin** [comment]
Придётся доказывать наличие глюка на тестовом сайте.

**Comment by ZTX18** [comment]
В файле _**core/components/pdotools/model/pdotools/pdotools.class.php**_
в _**public function buildTree**_ после перебора  _**foreach ($rows as $id => &$row) {...}**_ нужно

```
if (empty($tree)) {
    $tree = array_slice($rows,-1,1,true);
}
```

однако.

Почему именно на 2 левеле и в каких случаях последняя итерация не проходит не разбирался, но костыль проблему решает.

**Comment by bezumkin** [comment]
> Почему именно на 2 левеле и в каких случаях последняя итерация не проходит не разбирался, но костыль проблему решает.

Еще бы кто-нибудь смог доказать наличие этого "глюка". Лично я его до сих пор не вижу.

**Comment by ZTX18** [comment]
На [тестовом](http://s5062.h5.modhost.pro/) повторить **не** удалось. Видимо, нужны какие-то особо редкие условия... Так что да, на багу не тянет)
