### ISSUE TITLE
How to use Fenom on Resource or Template

### ISSUE THREAD

**Issue by adamwintle** [modx-pro/pdoTools#140]
I've tried the Fenom code on a chunk and this works; however, on a Template or a Resource, nothing is parsed. 

In the System Settings I have `pdotools_fenom_parser` = `yes`

This is the code I place into my Template:

```
$modx->runSnippet('pdoPage',array(
    'element' => 'getResources',
    'parents' => 0,
    'tpl' => 'article.panel.fenom',
    'pageLimit' => '3',
    'includeTVs' => 'first-image,portals',
));
```

**Comment by bezumkin** [comment]
Look at system log, there must an error of compile.

**Comment by bezumkin** [comment]
The most common error is incorrect syntax. It can also interfere JSON string, which is similar to the Fenom tag because opens with `{` - you need to avoid it. It can be snippet call of inline javascript in chunk or template.

```
{param: 'value'}
```

In this case you can just add space between `{` and string in JSON so Fenom will pass it.

```
{ param: 'value' }
```

**Comment by adamwintle** [comment]
I still don't understand how to run any snippet in a template using Fenom,

For example, I try this in a MODX Template:

```
{$_modx->runSnippet('MinifyX', [
    'minifyCss'         => 1,
    'registerCss'       => '1',
    'cssSources'        => ' ~ $_modx->config.assets_url ~ 'assets/css/main.css',
    'minifyJs'          => 1,
    'registerJs'        => '0'
])}
```

Yet on the output nothing is parsed, just output raw code.

**Comment by adamwintle** [comment]
And my System Setting is like this now, any error here: 

![screenshot 2015-09-01 00 48 09](https://cloud.githubusercontent.com/assets/167075/9585787/26fd5764-5043-11e5-9ad4-eb1ceea7941f.png)

**Comment by bezumkin** [comment]
Strange begin of concatenation in cssSources. I think you have another error in system log.

If you see raw tags - it is always an template compilation error.

**Comment by bezumkin** [comment]
Yes, you have wrong syntax for cssSources. That works for me:

```
{$_modx->runSnippet('MinifyX', [
    'minifyCss'         => 1,
    'registerCss'       => '1',
    'cssSources'        => $_modx->config.assets_url ~ 'assets/css/main.css',
    'minifyJs'          => 1,
    'registerJs'        => '0'
])}
```

**Comment by bezumkin** [comment]
Can I close this?

**Comment by adamwintle** [comment]
I still couldn't get the Fenom code to work on any MODX template - so I will come back to this later. 

Do you have demo code on any site?

**Comment by bezumkin** [comment]
What demo code do you need?

Just create blank template and write any Fenom code without typos and errors in system log. For example

```
{$_modx->config.site_name}
```

**Comment by adamwintle** [comment]
I have tried this, but it output without parsing on the front-end. 

This is inside a MODX template, without any pdoResources snippet; is this correct?

Any special System Setting need activating?

**Comment by adamwintle** [comment]
System Settings currently like this: 

![screenshot 2015-09-09 15 38 45](https://cloud.githubusercontent.com/assets/167075/9757150/e0de72dc-5708-11e5-94dc-8dde3c104b0d.png)

**Comment by bezumkin** [comment]
http://s2854.h4.modhost.pro/

```
Manager:   http://s2854.h4.modhost.pro/manager/
Login:     s2854
Password:  FtuVibHOVpcK
```

Content in [home page](http://s2854.h4.modhost.pro/manager/?a=resource/update&id=1)

```
{set $string = 'Hello, Fenom!'}

{$string}
```

[![](https://file.modx.pro/files/f/0/c/f0c24f77d0a10c1cc20ccd4a78fb6ea9s.jpg)](https://file.modx.pro/files/f/0/c/f0c24f77d0a10c1cc20ccd4a78fb6ea9.png) [![](https://file.modx.pro/files/2/4/5/2457329ca598994fc9704050ccdd6852s.jpg)](https://file.modx.pro/files/2/4/5/2457329ca598994fc9704050ccdd6852.png)

**Comment by adamwintle** [comment]
Thank you. I see nothing special, a very basic setup. 

I will try again on a fresh install. Maybe another plugin is conflicting.

**Comment by bezumkin** [comment]
@adamwintle can i close this issue?
