### ISSUE TITLE
When using Fenom "Unexpected token" in Error log

### ISSUE THREAD

**Issue by adamwintle** [modx-pro/pdoTools#142]
Since using Fenom templates the MODX Error Log now has many occurrences of this:

```
[2015-08-31 17:06:56] (ERROR @ /index.php) Unexpected token ',' in 3b510f939b78b6681b55cde64b345228 line 76, near '{3,' <- there
```

I have debug the script, and on the front-end they are find, but this error keep occurring many times. 

What is this? `3b510f939b78b6681b55cde64b345228`?

**Comment by bezumkin** [comment]
The [answer is here](https://github.com/bezumkin/pdoTools/issues/140#issuecomment-136414456).

3b510f939b78b6681b55cde64b345228 is tmp name made from content of template.

**Comment by adamwintle** [comment]
I use [HTML5 pattern](http://html5pattern.com/) on a form for minimum character input:

`<input pattern=".{3,}">`

Which causes the above MODX Error, I think this is conflicting with pdoTools Fenom. Should this with spaces fix it, or something better? 

`pattern=".{ 3, }"`

**Comment by bezumkin** [comment]
Yes, i think that must be enough.
