### ISSUE TITLE
How to use MODX input/output modifiers with Fenom? 

### ISSUE THREAD

**Issue by adamwintle** [modx-pro/pdoTools#143]
Is it possible to use the standard [MODX output modifiers](https://rtfm.modx.com/revolution/2.x/making-sites-with-modx/customizing-content/input-and-output-filters-%28output-modifiers%29) on the Fenom template tags? 

For example how can I apply this

`[[+introtext:ellipsis=`50`]]`

To this? 

`{$introtext}`

**Comment by bezumkin** [comment]
No, standard MODX output modifiers are hardcoded in [modOutputFilter](https://github.com/modxcms/revolution/blob/2.x/core/model/modx/filters/modoutputfilter.class.php).

You need to create your own snippet with this functionality and call it as

```
{$_modx->runSnippet('ellipsis', [
    'input' => $introtext,
    'length' => 50
])}
```

Maybe I will replace default filters somehow later.

**Comment by bezumkin** [comment]
By the way, some filters can be replaced by default Fenom functionality - [read the docs](https://github.com/fenom-template/fenom/blob/master/docs/en/syntax.md).

```
{set $string = '1234567890'}

{$string|truncate:5:"..."}
```

It will output

```
12345...
```

The whole [list of modifiers](https://github.com/fenom-template/fenom/tree/master/docs/en/mods)
