### ISSUE TITLE
Некорректная генерация URL в pdoPage

### ISSUE THREAD

**Issue by grachov** [modx-pro/pdoTools#145]
[Удалять цифровые ключи из ссылок](https://github.com/bezumkin/pdoTools/blob/master/core/components/pdotools/model/pdotools/pdopage.class.php#L175) - достаточно опрометчивое решение, они могут быть какими-то ID, например, а не просто порядковыми номерами:

``` php
$href .= preg_replace('/%5B\d+%5D/', '%5B%5D', http_build_query($request));
```

**Comment by bezumkin** [comment]
Это же [не просто так придумано](https://github.com/bezumkin/pdoTools/issues/81).

За 11 месяцев ты - первый, кому это решение не понравилось, так что прошу привести реальный пример некорректной работы.

**Comment by grachov** [comment]
Придумано кем? Человеком, который пытается сэкономить пару байт и пойти против стандарта?
Если есть форма с чекбоксами такого вида:

``` html
<div class="check-block clearfix">
    <input name="f[3][]" value="Male" type="checkbox" class="check" id="o55f174f96cfba-1" checked="checked" />
    <label for="o55f174f96cfba-1">MALE</label>
    <input name="f[3][]" value="Female" type="checkbox" class="check" id="o55f174f96cfba-2" />
    <label for="o55f174f96cfba-2">FEMALE</label>
    <input name="f[3][]" value="Kids" type="checkbox" class="check" id="o55f174f96cfba-3" />
    <label for="o55f174f96cfba-3">KIDS</label>
    <input name="f[3][]" value="International" type="checkbox" class="check" id="o55f174f96cfba-4" checked="checked" />
    <label for="o55f174f96cfba-4">INTERNATIONAL</label>
</div>
```

То ссылка постраничной навигации будет содержать `f[][]=Male&f[][]=International`, хотя 3 это был не просто индекс а идентификатор, и убирать его не было надобности.

**Comment by bezumkin** [comment]
Учитывая, что за всё это время "нарушение стандарта" (какого, кстати, можно ссылку?) помешало только тебе - жду готового решения.

**Comment by grachov** [comment]
Мне ничего не помешало, я естественно решил свою проблему, не надеясь получить адекватный ответ (что и произошло). Надеюсь, когда-то тебе встретится подобная форма/ссылка и ты изменишь свое мнение.
Ссылка на стандарт присутствует на странице, откуда было выдрано "не просто так придуманное" решение.

**Comment by bezumkin** [comment]
Какой адекватный ответ ты от меня ожидал? Вопрос я не закрыл, нафиг тебя не послал.

Повторяю еще раз, что **жду готового решения**. Пришлешь - добавлю в код (если там всё будет в порядке), не пришлёшь - всё останется как есть.

Если ты на меня обиделся и готов заплакать - просто сам закрой этот вопрос, без решения, я пойму.

**Comment by grachov** [comment]
Адекватный ответ представляет из себя попытку вникнуть в суть происходящего, а не отмахиваться фразами из разряда "у меня все работает".
Решение простое - использовать `http_build_query` в чистом виде, как это было до этого.
Самое интересное, что правка, ломающая нормальную генерацию URL была внесена без вопросов и разбирательств, а корректное решение необходимо отстаивать в таком ожесточенном бою. :smile:

**Comment by bezumkin** [comment]
> Адекватный ответ представляет из себя попытку вникнуть в суть происходящего, а не отмахиваться фразами из разряда "у меня все работает".

Да я так всегда делаю, ха-ха! Иначе с ума можно сойти, вникая во все проблемы, из которых реальных процентов 5. Поэтому и прошу **доказать** что-то и прислать PR.

Почему я принял тот коммит уже и сам не понимаю. Наверное, был занят чем-то еще.

> отстаивать в таком ожесточенном бою

Ой, не смешите мои тапочки, ожесточённый бой. Если бы сразу привёл свою форму и прислал исправление - принял бы без вопросов.
