### ISSUE TITLE
Обращение к multiCheckBox

### ISSUE THREAD

**Issue by vashot** [modx-pro/pdoTools#146]
Добрый день.
Вот бы простой способ обращаться к CheckBox Group поэлементно (option1==value1||option2==value2). Обращаться вроде такого: [[+tv.MyCheckBox.option1]]
Или это реализовано где-то?
Спасибо.

**Comment by bezumkin** [comment]
[prepareSnippet](https://bezumkin.ru/sections/components/1841/)
