### ISSUE TITLE
pdoResources не работает {$total}

### ISSUE THREAD

**Issue by faitno** [modx-pro/pdoTools#151]
Не работает вызов внутри чанка "tpl" вызов плейсхолдера {$total}, хотя, если рядом вызвать так:[[+total]] - все ок. Причем плейсхолдер {output} - работает.
Пример:

```
'tplWrapper'    => '@INLINE <ul class="thumbsMini">{$output} {$total} [[+total]]</ul>',
```

**Comment by bezumkin** [comment]
`[[+total]]` - это плейсхолдер, который MODX заменяет на значение **после** отработавшего сниппета.

Fenom работает за один проход и ничего после работы менять не может. Поэтому нужно указывать конкретное место, где взять значение:

```
{$_modx->getPlaceholder('total')}
```

**Comment by faitno** [comment]
действительно, работает, как же я сам не додумался. в итоге получилась такая симпатичная конструкция:

```
{$_modx->getPlaceholder("total") > 1 ? "{$output}" : ""}
```

Однако, по аналогии попытался вывести плейсхолдер [[!+page.nav]]

```
{$_modx->getPlaceholder('page.nav')}
```

но не работает... Хотя вот такой вызов:

```
[[!+page.nav]]
```

Конечно отдает все как надо.
