### ISSUE TITLE
sprintf() Too few arguments

### ISSUE THREAD

**Issue by hichnicksemen** [modx-pro/pdoTools#153]
Ошибка в логах и не работает Fenom

```
(ERROR @ /core/components/pdotools/model/fenom/Fenom/Template.php : 462) PHP warning: sprintf() [<a href='function.sprintf'>function.sprintf</a>]: Too few arguments
(ERROR @ /index.php) Fatal error while creating the template
```

**Comment by bezumkin** [comment]
Слишком мало данных для работы функции sprintf() - это не работает Fenom?

Учите английский, друзья. Нужно же понимать, что вам говорит компьютер.

**Comment by hichnicksemen** [comment]
Тогда не очень понятно в чём может быть дело, на странице выводится в не обработанном виде:

```
{if $modx->user->isAuthenticated($modx->context->key)}
    Юзер авторизован в контексте
{else}
    Это гость
{/if}
```

Все настройки включены, на других сайтах работает, может быть связано с настойками php у хостера?

Простите, что задаю вопрос тут и ещё как оказалось не в тему, думал ошибка проскочила.
