### ISSUE TITLE
Направление вывода

### ISSUE THREAD

**Issue by TITAN-UZ** [modx-pro/pdoTools#154]
Приветь

Пожалуйста добавте в pdoResources параметр &direction «ltr» / «rtl»

**Comment by bezumkin** [comment]
Что это и зачем?

**Comment by TITAN-UZ** [comment]
В pdoCrumbs ест этот параметр 
&direction   Направление навигации: слева направо «ltr» или справа налево «rtl», например для Арабского языка.

Ест категория там 11 новостей.
При выводе pdoResours выводить по убиванию 11-10-9
Если  в сортировке укажу &sortdir=`ASC` то выводит 1-2-3 
Параметр &idx и &first не работает 
Обсуждения тут https://modx.pro/help/6686/

**Comment by bezumkin** [comment]
Direction - это не сортировка, а стиль оформления. И применимо это только для хлебных крошек.

**Comment by TITAN-UZ** [comment]
Как бит тогда выводом в pdoResours?
