### ISSUE TITLE
pdoCrumbs: showHome

### ISSUE THREAD

**Issue by faitno** [modx-pro/pdoTools#156]
В сниппете pdoCrumbs параметр showHome=0 неправильно работает, когда настройка site_start не равна ID ресурса 1

**Comment by bezumkin** [comment]
Неправильно - это как? 

Там, вообще-то, просто [добавляется ресурс](https://github.com/bezumkin/pdoTools/blob/7fad32eb9d99a8178fdeb303d18b6ff6f403ef51/core/components/pdotools/elements/snippets/snippet.pdocrumbs.php#L58), указанный в [системной настройке site_start](https://github.com/bezumkin/pdoTools/blob/7fad32eb9d99a8178fdeb303d18b6ff6f403ef51/core/components/pdotools/elements/snippets/snippet.pdocrumbs.php#L33), никто не ищет id = 1.
