### ISSUE TITLE
Fenom обработка extends с параметрами

### ISSUE THREAD

**Issue by max4com** [modx-pro/pdoTools#157]
pdoTools 2.1.9-pl наблюдается нарушение работы шаблонизатора Fenom. При использовании настройки pdotools_fenom_parser и применении {extend 'template: название шаблона'} или {extend 'название чанка'}, шаблон или чанк который указан для extend'а проходит через parseChunk (в fenom/Providers/ModTemplate.php и fenom/Providers/ModChunk.php) и только после этого отдается fenom для проведения extend'а. Итог — полностью пропарсенный шаблон или чанк без изменений в блоках (так как в родительском шаблоне после парсера их уже не остается).

**Comment by bezumkin** [comment]
Насколько я вижу по коду, [обрабатываются только значения по умолчанию](https://github.com/bezumkin/pdoTools/blob/3a9f707ff85f16ac73ce89aafdeb021119b1cf85/core/components/pdotools/model/fenom/Providers/ModChunk.php#L45-L60), прописанные в свойствах чанка или шаблона.

Так и должно быть - на то они и умолчания.

**Comment by max4com** [comment]
Василий, к сожалению не могу проблему объяснить точнее, вот для примера сделал Демо сервер на modhost.pro - если будет время и желание можете посмотреть http://s3247.h4.modhost.pro/manager/  Логин: s3247 Пароль: 6uEUS4xiFkVR
(все элементы для примера сделаны), так же прошу обратить внимание на то как себя ведут {$_pls['testparam']} [[+testparam]] при первой загрузке с чистым кэшем и при перезагрузке страницы когда информация берется уже из кэша.

**Comment by bezumkin** [comment]
Да, ты прав, теперь я этот баг увидел. 

А по поводу пропадающего тега - точно такой же баг можно заметить, если сделать testparam некэшируемым:

```
[[!+testparam]]
```

Он так же пропадает при повторной загрузке из кэша и дело здесь вовсе не в pdoTools. Полагаю, проблема в том, что MODX не выставляет значения из наборов параметров в плейсхолдеры при загрузке элемента из кэша.

Решение одно - если хочется использовать эти дефолтные параметры у шаблонов, вместе с Fenom, придётся отключать кэш страницы.
