### ISSUE TITLE
Добавление модификаторов в fenom

### ISSUE THREAD

**Issue by faitno** [modx-pro/pdoTools#158]
Добрый вечер, подскажите, как довабить [свой модификатор](https://github.com/fenom-template/fenom/blob/master/docs/ru/ext/extend.md#Добавление-модификаторов) в fenom?
Я так полагаю, это нужно делать [в момент инициализации fenom'a](https://github.com/bezumkin/pdoTools/blob/f947b2abd9511919de56cbb85682e5d0ef52ebf4/core/components/pdotools/model/pdotools/pdotools.class.php#L123). Но только вот не нашел где именно это сделать. Направьте на путь истинный.

**Comment by bezumkin** [comment]
На данный момент такой возможности нет.

**Comment by faitno** [comment]
А ведь можно же [расширить класс](https://github.com/bezumkin/pdoTools/issues/27#issuecomment-31602321) pdoFetch, и в нем указать свои модификаторы для феном?
