### ISSUE TITLE
Вывод детей скрытых и не опубликованных родителей

### ISSUE THREAD

**Issue by akimsullec** [modx-pro/pdoTools#16]
При настройках по-умолчанию меню не строится, если опубликованные или доступные для меню ресурсы содержатся в parent, который скрыт для меню или не опубликован. 

Обходится включением showHidden и showUnpublished, но тогда все скрытые и неопубликованные элементы внутри родителя тоже выводятся в меню.
Можно обойти принудительным исключением этих ресурсов посредством "-", но это убивает автоматизацию.

Думаю, что правильнее чтобы в таком случае, дочерние элементы выводились вне зависимости от статуса парента, а вот статус самого парента влиял на displayStart.

**Comment by bezumkin** [comment]
Включаем логику: вот выбрали потомков, а родителя - нет. Куда пристраивать этих потомков в меню?
В корень меню, к другому родителю?

Если родитель скрыт или неопубликован - он не показывается со всеми потомками. Это нормальное поведение, точно такое же, как и у Wayfinder.

**Comment by akimsullec** [comment]
Это я написал потому что в вэйфайндере как раз так и работало - при скрытом родителе дети выводились.
Я ж по этому долго и не мог въехать - вроде названия сниппета и параметров изменить достатосно, чтобы pdoMenu заработал. Оказалось, что дело в разном поведении.

**Comment by bezumkin** [comment]
Он показывает, только если startId, но у pdoMenu может быть несколько parents, а не только 1.

В общем, понял тебя, подумаю как решить.
