### ISSUE TITLE
Неправильно работает scroll

### ISSUE THREAD

**Issue by kolengri** [modx-pro/pdoTools#161]
После последнего обновления ajaxmode=scroll перестал обновлять номер страницы в браузере и грузит постоянно вторую страницу выборки. ajaxmode=button вообще перестал работать.
Создал демо: http://s3312.h4.modhost.pro

**Comment by bezumkin** [comment]
Да, это после [вот этого PR](https://github.com/bezumkin/pdoTools/pull/160) - я поленился и не проверил.

**Comment by kolengri** [comment]
спасибо
