### ISSUE TITLE
Проблема с ajaxmode=button

### ISSUE THREAD

**Issue by kolengri** [modx-pro/pdoTools#162]
Привет. На одном из проектов (после обновления на 2.1.11 и 2.1.12) при нажатии на кнопку, после добавления результатов на страницу opacity не переключается на 1, всегда 0.3.
Пытался воспроизвести, не знаю в чем там проблема. Практически все настройки сниппета были подставлены в чанке.

Проблема решается просто: в 157 строчке else if заменил на if. На сколько понимаю это все-же бага?

``` javascript
            if (pdoPage.callbacks['after'] && typeof(pdoPage.callbacks['after']) == 'function') {
                pdoPage.callbacks['after'].apply(this, [config, response]);
            }
                  else if (config['mode'] != 'scroll') {// <<<<<<< 157
                wrapper.css({opacity: 1});
                if (config['mode'] == 'default') {
                    $('html, body').animate({scrollTop: wrapper.position().top - 50 || 0}, 0);
                }
            }
```

**Comment by bezumkin** [comment]
Нет, это не бага, это поведение скрипта по умолчанию, если не указаны свои собственные callbacks.

**Comment by bezumkin** [comment]
Ответа нет, закрываю.
