### ISSUE TITLE
pdoSitemap игнорирует link_tag_scheme в случае с https

### ISSUE THREAD

**Issue by max4com** [modx-pro/pdoTools#164]
В snippet.pdositemap.php жестко выставлено [sheme='full'](https://github.com/bezumkin/pdoTools/blob/master/core/components/pdotools/elements/snippets/snippet.pdositemap.php#L112), в связи с этим в случае использования протокола https и link_tag_scheme = 'abs' на сайте, ссылки генерируются все равно с http. Могли бы Вы добавить отдельный параметр scheme для pdoSitemap в котором будет возможность выбора между full и https?

**Comment by bezumkin** [comment]
А вот здесь почему работает? https://modstore.pro/sitemap.xml
Или здесь? https://modhost.pro/sitemap.xml

Может, стоит в системных настройках прописать base_url c https?

**Comment by max4com** [comment]
в таком случае в системных настройках надо прописать site_url ([для sheme='full'](https://github.com/bezumkin/pdoTools/blob/master/core/components/pdotools/elements/snippets/snippet.pdositemap.php#L112))

**Comment by bezumkin** [comment]
Да, верно. Не base_url, а site_url.
