### ISSUE TITLE
pdoResources &tvFilters needs support for default values

### ISSUE THREAD

**Issue by PuddingtonBeer** [modx-pro/pdoTools#168]
I was forced to revert to getResources simply because the pdo equivalent doesn't yet appear to support all the "new" operators, or default TV values (both allegedly available since getReources v1.4.2).

The lack of support for these features makes it seemingly impossible to use pdoResources when filtering by checkbox TV. I was unable to handle the case where the value of the TV has never been set. The box must first be checked, or checked and then unchecked in order for it to obtain a filterable value.

Checking for null also doesn't seem possible, despite getResources having an operator for that purpose ("IS", according to documentation). There is also a "null safe equals" according to the docs, "<=>".

**Comment by bezumkin** [comment]
Ok.

**Comment by pepebe** [comment]
Are there any plans to include tvFilters working with tv default values? Right now this doesn't seem to be supported.
