### ISSUE TITLE
Заменить $this->config['class'] на alias

### ISSUE THREAD

**Issue by Fi1osof** [modx-pro/pdoTools#169]
Василий, вот от такого лучше избавляться: https://github.com/bezumkin/pdoTools/blob/master/core/components/pdotools/model/pdotools/pdofetch.class.php#L310
Если передать class "sources.modMediaSource", к примеру, то в таком случае запрос получится select `sources.modMediaSource`.`id`..., что приведет к SQL-ошибке.

**Comment by bezumkin** [comment]
А зачем так передавать? Вот это у меня работает без проблем

```
[[!pdoResources?
    &class=`modMediaSource`
    &showLog=`1`
    &sortby=`id`
    &sortdir=`asc`
]]
```

**Comment by Fi1osof** [comment]
Это потому что MODX этот класс автоматом подгружает https://github.com/modxcms/revolution/blob/2.x/core/model/modx/modx.class.php#L443
Не очень корректный пример был с моей стороны.

ОК, будет реальный пример, покажу. Просто на эту проблему я уже натыкался. А пока просто уточню, что правильней получать алиас таблицы $alias = $this->query->getAlias() и его использовать.

**Comment by bezumkin** [comment]
Может так и неправильно, но есть еще опция &loadModels для загрузки моделей:

```
[[!pdoPage?
    &element=`pdoResources`
    &loadModels=`ms2gallery`
    &class=`msResourceFile`
    &sortby=`id`
    &sortdir=`asc`
]]
[[!+page.nav]]
```

**Comment by Fi1osof** [comment]
Сейчас лень искать проект, где возникнет эта проблема, но когда найду, маякну.

**Comment by bezumkin** [comment]
Видимо, проблем нет. Закрываю.
