### ISSUE TITLE
Баг после обновления 

### ISSUE THREAD

**Issue by shectermen** [modx-pro/pdoTools#171]
Доброго дня , сегодня после обновления pdoTools , pdoPage стал работать с адовым багом , он игнорирует параметр &limit указанный в вызове , вместо него limit равен количеству выводимых ресурсов , так же почему то все выводимые ресурсы дублируются

**Comment by bezumkin** [comment]
Ну а хоть как-то доказать наличие ошибки? Описать, как воспроизвести?

Больше жалоб нет, так что вряд ли это у pdoTools баг.

**Comment by shectermen** [comment]
Ну ребята в канале скайпа тоже сегодня жаловались на то что pdoPage странно себя ведет , чтобы воспроизвести надо просто вывести пагинацию с подгрузкой по кнопке , чтобы починить я откатился на 2 версии назад , тогда все заработало как надо , могу показать где так оно работает / дать доступы , сам ничего не модифицировал , просто обновился и все

**Comment by bezumkin** [comment]
Открываю [документацию, копирую код](http://docs.modx.pro/components/pdotools/snippets/pdopage#Загрузка-кнопкой), вставляю на страницу, проверяю - [и всё работает](https://cloud.githubusercontent.com/assets/1257284/11784185/39f65118-a2a5-11e5-945b-b56d0005e259.gif) (GIFка)

Ребята в скайпе, это, конечно, сильный аргумент при багрепортах.

**Comment by shectermen** [comment]
а почему тогда в моем частном случае так получилось ? сам ничего не менял , так же копировал код из документации , опять же почему нормально заработало после того как я откатился ?

**Comment by bezumkin** [comment]
Вы заявили, что есть баг. Я показываю, что сниппет работает как положено с примером из документации.

Что и почему где-то там у вас - я без понятия.
