### ISSUE TITLE
(вопрос) сортировка родителей по списку

### ISSUE THREAD

**Issue by justbekami** [modx-pro/pdoTools#173]
В сниппетах pdo при необходимости сортировки по определенному порядку используется связка
`
&resources='список'
&sortby=''
`

Но можно ли реализовать схожую задачу (сортировка по произвольному списку) для параметра parents?

Грубо говоря, при пустом sortby в методе pdoFetch::addSort() проверять условие, если параметр resources пустой, но не пустой список родителей выборки - сортировать по нему.

**Comment by bezumkin** [comment]
Можно указать вручную сортировку по любому полю вот так:

```
&sortby=`FIELD(modResource.parent, 5,6,4,7,8)`
```
