### ISSUE TITLE
[pdoUsers] Не устанавливается плэйсхолдер при &returnIds=`1`

### ISSUE THREAD

**Issue by ViieeS** [modx-pro/pdoTools#176]
Заметил несколько недочетов в работе сниппета.

При указание свойства &returnIds=`1`, плэйсхолдер не устанавливается.

```
[[!pdoUsers?
    &groups=`Group`
    &roles=`Role`
    &returnIds=`1`
    &toPlaceholder=`somePlaceholder`
]]
```

решить можно через встроенные modx фильтры:

```
[[!pdoUsers:toPlaceholder=`somePlaceholder`?
    &groups=`Group`
    &roles=`Role`
    &returnIds=`1`
]]
```

Ну и в довесок,
@INLINE не работает внутри шаблона вызова другого сниппета, (например pdoResources), наверное проблема комплексная для всего pdoTools.
#### tpl.mFilter2.outer

```
[[!pdoUsers?
    &groups=`Group`
    &roles=`Role`
    &tpl=`@INLINE <p>Имя - [[+fullname]], ID - [[+id]]</p>`
    &toPlaceholder=`somePlaceholder`
]]
```

**Comment by bezumkin** [comment]
С @INLINE чанками никаких проблем нет, особенно если [знать особенность их работы](http://docs.modx.pro/components/pdotools/general-settings#Способы-вызова-чанков).

Но даже и так у меня всё в порядке.
[![](https://file.modx.pro/files/d/6/7/d6702e4f4de54bf42949aa3181f1d1bfs.jpg)](https://file.modx.pro/files/d/6/7/d6702e4f4de54bf42949aa3181f1d1bf.png) [![](https://file.modx.pro/files/0/2/4/0245d292d93dbc813ef4131608588f84s.jpg)](https://file.modx.pro/files/0/2/4/0245d292d93dbc813ef4131608588f84.png)
