### ISSUE TITLE
Ошибка в index.php при включения Fenom

### ISSUE THREAD

**Issue by TITAN-UZ** [modx-pro/pdoTools#177]
Здравствуйте при включения pdotools_fenom_parser то в логах выводит ошибку

(ERROR @ /index.php) Unexpected tag 'i' in 0a6a76ea27c1b18cd8b33da759a5a818 line 38, near '{i[' <- there

Как бить

**Comment by bezumkin** [comment]
https://modx.pro/components/6223-pdotools-version-2-1-improve-fenom/#comment-45360
