### ISSUE TITLE
MobileDetect

### ISSUE THREAD

**Issue by TITAN-UZ** [modx-pro/pdoTools#178]
Здравствуйте

Внутри тегов MobileDetect fenom не обрабатывается просто выводить тег

**Comment by TITAN-UZ** [comment]
Можете закрыт!
Если в чанках мобильной версии ест js код то FENOM не обрабатывать теги

**Comment by bezumkin** [comment]
https://github.com/fenom-template/fenom/blob/master/docs/ru/tags/ignore.md
