### ISSUE TITLE
&totalVar doesn't take care of &limit

### ISSUE THREAD

**Issue by jchirschy** [modx-pro/pdoTools#183]
The placeholder `&totalVar` returns the number of results regardless of the `&limit` specified.

**Comment by bezumkin** [comment]
That is why it called **total**.

**Comment by jchirschy** [comment]
Hello,

In some cases, you have to know how many resources will be displayed, not how many resources match the criteria. For example, when you have to manage indicators in a carousel. Maybe, it would be convenient to get a `&totalDisplayedVar` which takes care of `&limit` specified in the snippet's call.

**Comment by bezumkin** [comment]
You can calculate it yourself using total, limit and number of page.

```
[[!pdoPage?
    &parents=`0`
    &limit=`13`
    &totalVar=`total`
]]
[[!Calculate?limit=`13`]]
```

Snippet Calculate:

``` php
<?php
$limit = $modx->getOption('limit', $scriptProperties, 10);
$total = $modx->getOption('total', $scriptProperties, $modx->getPlaceholder('total'));
$page = $modx->getOption('page', $scriptProperties, $modx->getPlaceholder('page'));

$remains = $total - ($page * $limit);

return $remains >= 0
    ? $limit
    : $limit - abs($remains);
```
