### ISSUE TITLE
tvFilters не рабоает с некоторыми полями

### ISSUE THREAD

**Issue by Skippidar** [modx-pro/pdoTools#185]
Есть следующий  вызов:

```
[[pdoResources?
                            &parents=`[[*id]]`
                            &where=`{"template:=":"7"}`
                            &limit=`6`
                            &tpl=`tpl.catalog.item`
                            &includeTVs=`product.price, product.price.old, thumbnail, product.size`
                            &totalVar=`total.items`
                            &tvFilters=`product.price.old!==2000`
                            &sortby=`publishedon`
                            &sortdir=`DESC`
                        ]]
```

Если указать "&tvFilters=`product.price!==2000`" то спокойно выводит правильные товары. Но вот &tvFilters=`product.price.old!==2000` выдает ошибку в логи: "Unknown column 'TVproduct.price.value.old' in 'where clause'"

**Comment by bezumkin** [comment]
Попробуйте первести, что вам пишут

> Unknown column 'TVproduct.price.value.old' in 'where clause'

Потом подумать, проверить всё, и указать 

```
product.price_old
```

**Comment by Skippidar** [comment]
Это то само собой поможет. Но это разве не баг, что нельзя написать product.price.old? Изменить то название можно, но тогда перелопачивать весь проект и изменять вызовы этого TV?  Если это такая фича, то надо тогда в документации написать о том что подобная запись названия tv неприемлема, ибо я на многих проектах встречал такую запись и там не 3й вложенности, а 5й и 6й встречались.

**Comment by bezumkin** [comment]
&tvFilters всего-лишь переводит значения в нормальный параметр &where и нужен исключительно для плавного перехода с getResources.

Читайте [документацию по &where](http://docs.modx.pro/components/pdotools/classes/pdofetch#Метод-addWhere) там можно указывать что угодно.

Как-то улучшать или менять работу &tvFilters я не планирую, ибо это тупой костыль для ленивых людей. Если исправите эту свою ошибку и пришлёте PR - добавлю.

**Comment by Skippidar** [comment]
Я уже просто как-то давно исправлял багу с наличием пробелов в названии tv, Но этот коммит был просто удален)

**Comment by bezumkin** [comment]
Нет, [не удалён](https://github.com/bezumkin/pdoTools/pull/127). Больше подобных вопросов не было, так что он так и висит.

Вообще интересно, поему только у вас такие вопросы появляются. Хотя нет, неинтересно. В общем, я тут ничего делать не буду, а вы как хотите.
