### ISSUE TITLE
where и числовые TV

### ISSUE THREAD

**Issue by Skippidar** [modx-pro/pdoTools#195]
Есть объекты, у которых указана стоимость, есть фильтры этих объектов по диапазону цен (указываем либо минимальную, либо максимальную, либо обе)
Выводятся они с помощью pdoResources, у которого параметр where генерируется сниппетом (если фильтры не указаны - выводятся все объекты). Строка следующего вида:
`{"template:=":"15","TVflat-price.value:<=":3852145}` 
выводит все объекты стоимость которых меньше указанного числа, однако если этому числу в начале поставить "1", чтобы получилось 
`{"template:=":"15","TVflat-price.value:<=":13852145}` 
то даже те объекты что выводились до этого - не выводятся.
Это всё объясняется тем что сравнение идет не числовых переменных, а строковых (цен меньше 1900000 нет)

Собственно вопрос: что тогда нужно указывать чтоб сравнение шло не как строк, а как чисел. TV имеют тип "Число", в строке where числа указаны без кавычек.

**Comment by Skippidar** [comment]
Помогает подстановка перед числом знака "+" или "-", однако если TV может быть и >0 и <0 - уже придется добавлять проверку ставить + или нет. Но вариант рабочий.

**Comment by bezumkin** [comment]
Можно указывать строку с условиями внутри одномерного JSON массива, вот так:

```
[[!pdoResources?
    &parents=`0`
    &select=`id`
    &includeTVs=`Number`
    &where=`["Number > 0"]`
    &showLog=`1`
]]
```

Тогда получается примерно такой запрос:

``` sql
SELECT SQL_CALC_FOUND_ROWS `modResource`.`id`, IFNULL(`TVnumber`.`value`, '') AS `tv.Number` FROM `mysql_site_content` AS `modResource` LEFT JOIN `mysql_site_tmplvar_contentvalues` `TVnumber` ON `TVnumber`.`contentid` = `modResource`.`id` AND `TVnumber`.`tmplvarid` = 1 WHERE  ( `TVnumber`.`value` > 0 AND `modResource`.`published` = 1 AND `modResource`.`deleted` = 0 )  ORDER BY modResource.publishedon DESC LIMIT 10
```

Здесь значение сравнивается с числом, а не строкой.
