### ISSUE TITLE
Ошибка в pdoCrumbs после обновления 

### ISSUE THREAD

**Issue by radist** [modx-pro/pdoTools#198]
Fatal error: Call to undefined method pdoFetch::makeUrl() in /home/.........../public_html/core/cache/includes/elements/modsnippet/31.include.cache.php on line 153

31.include.cache.php - это pdoCrumbs

**Comment by bezumkin** [comment]
Удалить пакет, поставить снова - помогает.

**Comment by bezumkin** [comment]
Ответа нет, закрываю.
