### ISSUE TITLE
pdoResources сортировка по числовому ТВ

### ISSUE THREAD

**Issue by Skippidar** [modx-pro/pdoTools#200]
Добрый день. имеется следующий вызов pdoResources:
`[[!pdoResources? 
                            &parents=`[[+docid:is=`:then=`[[*id]]`:else=`[[+docid]]`]]`
                            &limit=`[[+limit:is=`:then=`6`:else=`[[+limit]]`]]`
                            &where=`{"template:=":"7"}`
                            &includeTVs=`product.price, product.price_old, thumbnail, product.size, product.saloon`
                            &tpl=`tpl.catalog.item`
                            &includeContent=`1`
                            &sortby=`[[+sortby:is=`:then=`pagetitle`:else=`[[+sortby]]`]]`
                            &sortdir=`[[+sortdir:is=`:then=`ASC`:else=`[[+sortdir]]`]]`
                            &tvFilters=`[[+filter]]`
                            &offset=`[[+offset:is=``:then=`0`:else=`[[+offset]]`]]`
                            &totalVar=`total.items`
                        ]]`

Если sortby передавать 'product.price' (у поля тип "Число"), то сортировка работает, но как для строк - 10000000 считается меньше 999

Собственно, хотелось бы узнать - это я где-то что-то упустил, или есть способ указать что сортировка числовая?

**Comment by bezumkin** [comment]
Попробуйте [документацию почитать](http://docs.modx.pro/components/pdotools/general-settings)

**Comment by Skippidar** [comment]
Спасибо, не знал что есть еще и этот раздел документации. искал в http://docs.modx.pro/components/pdotools/snippets/pdoresources - там про sortbyTVType ничего

**Comment by Skippidar** [comment]
Вот только в документации написано "Если пусто, то ТВ будет отсортирован в зависимости от его типа: как текст, число или дата.", а у меня тип поля и выбран "Число"

Хорошо, подставил в вызов &sortbyTVType=`[[+sortby:is=`product.price`:then=`integer`]]`

В итоге получается вызов со следующими параметрами (вывел все параметры вызова):
&parents=`246` 
&limit=`6` 
&where=`{"template:=":"7"}` 
&includeTVs=`product.price, product.price_old, thumbnail, product.size, product.saloon` 
&tpl=`tpl.catalog.item` 
&includeContent=`1` 
&sortbyTV=`product.price` 
&sortdirTV=`DESC` 
&sortbyTVType=`integer` 
&tvFilters=`product.price_old!=,product.price_old!=0` 
&offset=`0` 
&totalVar=`total.items`

Но 94500 по прежнему считается больше чем 900000 
Уж новый issue думаю смысла нету открывать

**Comment by bezumkin** [comment]
Есть волшебный параметр, называется showLog - он показывает, как проходит работа сниппета.

Там можно увидеть много всего полезного, в том числе и SQL запрос.

**Comment by Skippidar** [comment]
Проблема оказалась в наличии точки в названии TV.
Проверил на чистой установке modx - по полю price сортировка string и integer различаются, а при сортировке по price.price  - сортировка и в 1м и во 2м случае строковая.
