### ISSUE TITLE
pdoMenu and ContentBlocks

### ISSUE THREAD

**Issue by mw-web-design** [modx-pro/pdoTools#202]
I'm using pdoTools and ContentBlocks from modmore together - some things are working fine.
My code is like that:

```
[[pdoMenu? &parents=`7` &level=`1` &tplOuter=`@INLINE [[+wrapper]]` &tpl=`@INLINE [[!cbGetFieldContent? &field=`19` &resource=`[[+id]]`]]`]]
```

And I get the right fields - great!
But when I have a ContentBlocks filter inside like this the output is wrong:

```
[[pdoMenu? &parents=`7` &level=`1` &tplOuter=`@INLINE [[+wrapper]]` &tpl=`@INLINE [[!cbGetFieldContent? &field=`19` &resource=`[[+id]]` &fieldSettingFilter=`cat1==Digital`]]`]]
```

So my question is: Does have pdoMenu a problem to work with == ?
Thanks for help!
Mike

**Comment by bezumkin** [comment]
Try to not use INLINE chunk in this case. Make a normal chunk with your condition

**Comment by mw-web-design** [comment]
Hi Vasily ,
thank you very much for the fast response :-)
I've tried it without INLINE but it does not work - as soon I use the filter with == it seems that &tpl will be ignored.
Any ideas are welcome...
Mike

**Comment by bezumkin** [comment]
Than maybe you need to ask this question in the ContentBlock repository?

**Comment by mw-web-design** [comment]
Hi Vasily,

I think it’s a problem of pdoTools – also when I use a string output modifier like [[+menutitle:replace=`1==2`]] inside &tpl it doesn’t work – for example :limit=`50` works but as soon == is in use it break down.

Mike

Von: Vasily Naumkin [mailto:notifications@github.com] 
Gesendet: Freitag, 8. April 2016 12:33
An: bezumkin/pdoTools
Cc: mw-web-design
Betreff: Re: [bezumkin/pdoTools] pdoMenu and ContentBlocks (#202)

Than maybe you need to ask this question in the ContentBlock repository?

**Comment by bezumkin** [comment]
It is not works only in INLINE chunks because of parser can`t handle it on page. But when i put this condition into regular chunk - everything is okay.

For example - here is my resources, you can see snippet call
![](https://file.modx.pro/files/7/9/3/7934f89f690e9bbfa8386e20e75c8f38.png)
Here is my chunk Test:

```
<p>[[+idx]]. [[+pagetitle:replace=`pdo==xxx`]]
```

And here is result:
![](https://file.modx.pro/files/6/4/8/6488a2c5308fbf19fe103db6803e4e1e.png)
