### ISSUE TITLE
tvFilters and default values

### ISSUE THREAD

**Issue by pepebe** [modx-pro/pdoTools#206]
There is a closed topic with a similar problem: https://github.com/bezumkin/pdoTools/issues/168

Question: Are there any plans to support tv default values in tvFilters? Right now this doesn't seem to be supported.

**Comment by bezumkin** [comment]
No, there is no such plans.

More info about my logic - http://modx.today/posts/2016/04/pdotools-introduction-(part-2)

**Comment by pepebe** [comment]
Hi, and thank you for the link. It was extremely useful. I wish I didn't miss it before.

Cheers, Patrick

**Comment by bezumkin** [comment]
You are welcome!

I hope that @mark-h will publish the final 3rd part of those articles soon.
