### ISSUE TITLE
Плейсходер total для pdopage

### ISSUE THREAD

**Issue by vgrish** [modx-pro/pdoTools#21]
если число общих элементов нечетное, а limit четный, то total в pdopage на 1 больше.

**Comment by bezumkin** [comment]
Не могу воспроизвести
<img src="http://st.bezumkin.ru/files/e/4/2/e420cf1dbcc284e7435cdd52859608f8.png" />

**Comment by vgrish** [comment]
сейчас по новой тестовый завел и все повторил... все ОК!
Наверно я что-то начудосил, извини за беспокойство.

**Comment by bezumkin** [comment]
Может, у тебя там еще где пагинация была и плейсхолдер просто заменялся.

В новой версии можно будет указывать имя этой переменной.
