### ISSUE TITLE
&offset doesn't seem to do anything

### ISSUE THREAD

**Issue by pdincubus** [modx-pro/pdoTools#210]
I'm trying to use &offset to start from the second item in a call so that I can show a "featured" item on a page, and then a list further down the page which doesn't show that first item.

I've tried both cached and uncached calls and neither seem to respect the offset parameter, the second call just outputs all the items.

Am I missing something?

Code is:

```
[[!pdoResources?
    &parents=`[[*id]]`
    &tpl=`template`
    &limit=`0`
    &offset=`1`
    &includeTVs=`TVS`
    &sortbyTV=`TVNAME`
    &sortdirTV=`ASC`
    &sortbyTVType=`datetime`
]]
```

**Comment by bezumkin** [comment]
Try to debug you call by enable

```
&showLog=`1`
```

Maybe offset won`t work with limit = 0

**Comment by pdincubus** [comment]
Thanks, I added a limit of 20 and it seems to now work.
