### ISSUE TITLE
pdoPage 

### ISSUE THREAD

**Issue by Skippidar** [modx-pro/pdoTools#211]
Есть следующий вызов:

```

                            <div id="pdopage">
                                <div class="rows items">
                                    [[!pdoPage?
                                        &parents=`0`
                                        &where=`{"template:=":"15"}`
                                        &limit=`9`
                                        &tpl=`tpl.flat-list.flat`
                                        &includeTVs=`flat-type,flat-square-total,flat-price,plan,flat-ready`
                                        &totalVar=`total-found`
                                        &pageVarKey=`filter-flats-[[*id]]`
                                        &ajaxMode=`button`
                                        &ajaxElemWrapper=`#pdopage`
                                        &ajaxElemRows=`#pdopage .rows`
                                        &ajaxElemPagination=`#pdopage .pagination`
                                        &ajaxElemLink=`#pdopage .pagination a`
                                        &ajaxElemMore=`#pdopage .load-more`
                                        &ajaxTplMore=`@INLINE <div class="commercial-apartaments-showMore load-more">Показать ещё</div>`
                                    ]]
                                </div>
                                [[!+page.nav]]
                            </div>
```

Если его вызывать в шаблоне - всё корректно отображается, но если его подгружать ajax-ом - ничего не выводит. 
Однако если убрать ajaxMode чтоб выводило с обычной постраничной навигацией - всё выводится корректно, а вот с включенным ajax - всё пусто
Причем с &showLog=`1` тоже пусто. А в журнал ошибок ничего не пишет.

**Comment by bezumkin** [comment]
Если сниппет сам загружается через ajax, как он подключит свои скрипты?

**Comment by Skippidar** [comment]
А есть тогда какой-либо метод чтоб перезагрузить скрипты?

**Comment by bezumkin** [comment]
Да, загрузить их вручную в шаблоне.

**Comment by Skippidar** [comment]
Тоесть достаточно просто подгрузить assets/components/pdotools/js/pdopage.js ?

**Comment by bezumkin** [comment]
По идее - да, но не проверял. Можно загрузить и свой скрипт, который будет обрабатывать запросы [согласно документации](http://docs.modx.pro/components/pdotools/snippets/pdopage#Поддержка-Ajax).

**Comment by Skippidar** [comment]
Просто непонятно. По логике, даже без скриптов сниппет должен хоть что-то показывать, тем более если указано &showLog=`1`
Но его вообще нет.
И добавил при загрузке 

```
$.getScript( "/assets/components/pdotools/js/pdopage.js", function( data, status, jqxhr ) {});
```

а ничего и не поменялось

**Comment by bezumkin** [comment]
Не судьба, значит.
