### ISSUE TITLE
pdoNeighbors issues

### ISSUE THREAD

**Issue by mtalvenheimo** [modx-pro/pdoTools#213]
Hi,
In version 1.9.2 pdoNeighbors was hidden by default when resource had no siblings. (Parent had only one children). Also in first and last resource of siblings didn't have next & prev buttons. (From last to first, from first to last)

In version 2.4.0 pdoNeighbors is showing prev-link even if resource don't have siblings. Links to itself. Also by default it "loops" from last to first resource.

Is there a way to hide Neighbors if lonely resource? And opt out the looping?

**Comment by bezumkin** [comment]
Did you try?

```
&loop=`0`
```

**Comment by mtalvenheimo** [comment]
No. It works! Thanks.
How about if there's only one children?

**Comment by mtalvenheimo** [comment]
Oh sorry. That ofcourse solved this issue also.
Thanks = Solved
