### ISSUE TITLE
tvFilters неправильно сравнивают значения.

### ISSUE THREAD

**Issue by agragregra** [modx-pro/pdoTools#214]
Здравствуйте.
При использовании pdoResources следующая проблема.
Задаю в tvFilters=`param==20`, все отлично фильтруется.
Задаю в tvFilters=`param<=20`, показываются все значения, меньше 20 и больше 100. Почему-то сниппет считает, что 100 - это 10, вероятно и что 100 меньше 20.
Однако, при использовании getResources все фильтруется правильно.

**Comment by bezumkin** [comment]
https://github.com/bezumkin/pdoTools/issues/195

**Comment by wdmcourses** [comment]
А можете реализовать сравнение не через where, а как положено? На примере getResources, там же работает такое сравнение? Если нет, какова причина?

**Comment by bezumkin** [comment]
Положено как раз через where.

tvFilters сделан для криворуких неумех, которые не понимают SQL и JSON. А внутри оно [всё равно превращается в where](https://github.com/bezumkin/pdoTools/blob/8a0d050a229230c6f88a44b87cfbd7c9e9ce4b62/core/components/pdotools/model/pdotools/pdofetch.class.php#L910-L911).

Если что-то не устраивает - используйте getResources.

**Comment by wdmcourses** [comment]
Воспользовался вашим советом. Спасибо.
`'where' => $modx->toJSON(array($filter))`
