### ISSUE TITLE
Установка кода состояния

### ISSUE THREAD

**Issue by mishanthrop** [modx-pro/pdoTools#215]
Я использую pdoPage для постраничного вывода записей. 
Если перейти на заведомо несуществующую страницу (site.ru/articles/page/100500), то отдаётся заголовок 302 и происходит перенаправление на первую страницу. 
Как установить в данном случае код ответа не 302, а 404?

**Comment by bezumkin** [comment]
Никак.

**Comment by mishantrop** [comment]
Пидрил

**Comment by mishanthrop** [comment]
Почему? Какие-то технические ограничения?
