### ISSUE TITLE
pdoResources limit и total

### ISSUE THREAD

**Issue by Skippidar** [modx-pro/pdoTools#216]
при указании &limit, [[+total]] показывает сколько всего найдено элементов, в итоге условие [[+idx:is=`[[+total]]`:then=`</div>`]] не срабатывает. 

Как тогда можно проверить что текущий элемент - последний для вывода? Есть какой-нибудь [[+last]], а то я не смог найти чего-то похожего?

**Comment by bezumkin** [comment]
Неужели [всех этих чанков не хватает](http://docs.modx.pro/components/pdotools/snippets/pdoresources#Параметры-шаблонов)?

**Comment by Skippidar** [comment]
Просто иногда бывает верстка где элементы сгруппированы разными способами и нужно допустим у каждого 3го элемента если он 5й в дедовском элементе... и т.д. и вот тогда мне кажется проще это все в одном чанке условиями проверять на основании idx, нежели пытаться разбивать одно и то же по чанкам. В принципе то если указать limit=0 то будет всё нормально, [[+total]] будет равен idx последнего элемента, но отображать так сотню элементов - скажется на загрузке сайта =)
