### ISSUE TITLE
Weblinks and active Elements in pdoMenu

### ISSUE THREAD

**Issue by pepebe** [modx-pro/pdoTools#218]
pdoTools 2.4.0pl on MODx2.5

Not sure if this is a bug or a feature.

My Sitestructure:

```
Link 1 (weblink to Sublink 1.1 below)
-- Sublink 1.1
-- Sublink 1.2
-- Sublink 1.3
Link 2 (normal document)
-- Sublink 2.1
-- Sublink 2.2
-- Sublink 2.3
```

What I would expect: The chain of active li elements gets from the root all the way down to the current resource.

What happens: If a parent resources is a weblink to a childresource, the chain is broken for the siblings of the target resource.

Example:

Result for example.com/link1/sublink1.1.html

```
<ul>
-- <li  class="active"> <!-- OK! -->
-- Link 1
-- <ul>
-- -- <li  class="active">Sublink 1.1</li>
-- -- <li>Sublink 1.2</li>
-- -- <li>Sublink 1.3</li>
-- </li>
-- <li>
-- <ul>
-- -- <li>Sublink 1.1</li>
-- -- <li>Sublink 1.2</li>
-- -- <li>Sublink 1.3</li>
-- </li>
```

Perfect!!!

Result for example.com/link1/sublink1.2.html

```
<ul>
-- <li> <!-- Missing active class -->
-- Link 1
-- <ul>
-- -- <li>Sublink 1.1</li>
-- -- <li  class="active">Sublink 1.2</li>
-- -- <li>Sublink 1.3</li>
-- </li>
-- <li>
-- Link 2
-- <ul>
-- -- <li>Sublink 2.1</li>
-- -- <li>Sublink 2.2</li>
-- -- <li>Sublink 2.3</li>
-- </li>
```

Error: Link 1 (the parent of sublink 1.2) isn't active anymore. The same thing happens for sublink 1.3.

Result for example.com/link2/sublink2.1.html

```
<ul>
-- <li>
-- Link 1
-- <ul>
-- -- <li>Sublink 1.1</li>
-- -- <li>Sublink 1.2</li>
-- -- <li>Sublink 1.3</li>
-- </li>
-- <li>
-- Link 2
-- <ul class="active">
-- -- <li>Sublink 2.2</li>
-- -- <li class="active">Sublink 2.2</li>
-- -- <li>Sublink 2.2</li>
-- </li>
```

OK.

Regards,

pepebe

**Comment by darQrrR** [comment]
Having this exact issue (again) with in MODX 2.8.5 / pdoTools 2.13.3 as well as in MODX 3.0.1 / pdoTools 3.0.2
