### ISSUE TITLE
link rel="rpev|next"

### ISSUE THREAD

**Issue by f104** [modx-pro/pdoTools#22]
https://support.google.com/webmasters/answer/1663744?hl=ru
Понятно, что каждый может это сделать самостоятельно, но было бы здорово добавить этот функционал в сниппет.
Плюс один параметр и один вызов $modx->regClientStartupHTMLBlock.
Спасибо.

**Comment by bezumkin** [comment]
<blockquote>Можно использовать HTML атрибуты rel="next" и rel="prev" , чтобы указать связь между отдельными URL. Благодаря этой разметке Google может определить, что содержание данных страниц связано в логической последовательности.</blockquote>

Это подходит для разбивки одной большой страницы на подстаницы.

Сниппет  pdoNeighbors выводит ссылки на соседние документы. Они не связаны логически, они просто находятся в одном разделе.

Ну и первым советом идёт "не совершать действия"

<blockquote>Поскольку разбиение на страницы используется очень часто, алгоритмы Google возвращают содержание, наиболее соответствующее запросам пользователей, независимо от того, на скольких страницах оно расположено.</blockquote>

**Comment by f104** [comment]
Сорри, я, конечно же, имел в виду этот функционал для pdoPage.
PS: Спасибо за вашу работу с MODx.

**Comment by bezumkin** [comment]
Ну и там тоже самое, даже хуже:
- любые, абсолютно любые данные, которые не пойми как связаны друг с другом
- и может быть несколько пагинаций на одной странице - тогда что?

В общем, предлагаю этот функционал в стандартную поставку не включать.
