### ISSUE TITLE
pdoFetch 5mb! big modx resourse map

### ISSUE THREAD

**Issue by SlivaNilow** [modx-pro/pdoTools#222]
Hi, we have more than 30 000 items on site
and when we use pdoResources  CPU usage 100%
debug show what pdoFetch dump return 5mb text - all modx resource map

$pdoFetch = new $pdoClass($modx, $scriptProperties);

Доброго времени суток.
На сайте более 30 тысяч страниц. и когда используется pdoResources - то процессор грузится на 100%. все тормозит. Дебаг показал что при создании pdoFetch - переменная содержит всю карту ресурсов модх. аж на 5 мегабайт. Как можно обойтись без передачи в pdoClass всего объекта $modx а например ссылки на него?

Что то вообще не понимаю..не смотря на объем
делаю после вызова die

```
$rows = $modx->runSnippet('pdoResources', $scriptProperties);
die;
```

процессор грузится

делаю die перед последним ретурном в снипете pdoResources - не грузится. что за чудеса

```
    }

    if (!empty($toPlaceholder)) {
        $modx->setPlaceholder($toPlaceholder, $output);
    } else {
var_dump($output);
die;
        return $output;
    }
}
```

по идее то return сразу идет в переменную что выше.

**Comment by SlivaNilow** [comment]
В общем дальнейший дебаг показал подобную фигню

```
0.0002620: pdoTools loaded
0.0000510: xPDO query object created
0.0009539: Added selection of <b>modResource</b>: <small>SQL_CALC_FOUND_ROWS `id`, `type`, `contentType`, `pagetitle`, `longtitle`, `description`, `alias`, `link_attributes`, `published`, `pub_date`, `unpub_date`, `parent`, `isfolder`, `introtext`, `richtext`, `template`, `menuindex`, `searchable`, `cacheable`, `createdby`, `createdon`, `editedby`, `editedon`, `deleted`, `deletedon`, `deletedby`, `publishedon`, `publishedby`, `menutitle`, `donthit`, `privateweb`, `privatemgr`, `content_dispo`, `hidemenu`, `class_key`, `context_key`, `content_type`, `uri`, `uri_override`, `hide_children_in_tree`, `show_in_tree`, `properties`</small>
9.4441741: Processed additional conditions
9.4709208: Added where condition: <b>template:==5, modResource.parent:IN(74,103,104,105,106,107,108,29064,126,12748,13049,13201,13285,14018,16655,18784,22954,26924,12749,12751,12777,12795,12802,12825,12830,12848,12890,12905,12906,12957,12968,12982,20505,28671,28721,16856,16836,16837,16838,16839,16840,16841,16842,16843,16844,16845,16846,16847,16848,16849,16850,16851,16852,16853,16854,16855,16857,16858,16859,16860,16861,16862,16863,16864,16865,16866,16867,12752,12753,12754,12755,12756,12757,12758,12759,12760,12761,12762,12763,12764,12765,12766,12767,12768,12769,12770,12771,12772,12773,12774,12775,12776,12778,12779,12780,12781,12782,12783,12784,12785,12786,12787,12788,12789,12790,12791,12792,12793,12794,12796,12797,12798,12799,12800,12801,12803,12804,12805,12806,12807,12808,12809,12810 и еще очень много
```

Понимание все хуже и хуже

```
public function runSnippet($snippetName, array $params= array ()) {

        $output= '';
        if ($this->getParser()) {
            $snippet= $this->parser->getElement('modSnippet', $snippetName);
            if ($snippet instanceof modSnippet) {
                $snippet->setCacheable(false);
                $output= $snippet->process($params);
            }
        }
var_dump($output);
        die;
        return $output;
    }
```

все возвращает. нагрузка нормальная...дело не в pdoResources

Буду копать модх

**Comment by SlivaNilow** [comment]
Извиняюсь

**Comment by bezumkin** [comment]
Ок =)

**Comment by SlivaNilow** [comment]
Докопался до тормозящего компонента.
pdoFetch использует `$this->modx->getChildIds($k, $depth, array('context' => $v)));`
а тот в свою очередь ищет все в карте ресурсов рекурсивно. без фильтрации. просто возвращает все возможные id

Получается что с большой структурой каталогов всегда будут тормоза и большая нагрузка.
Переделывал поиск в карте ресурсов на запросы - еще хуже. 
Отправил тикет в ветку модх

Попробую сделать процедуру в mysql - может будет побыстрее, или добавить фильтрацию в getChildIds

**Comment by bezumkin** [comment]
Есть параметр &depth, который ограничивает глубину выборки.
Есть возможность указывать напрямую ресурсы для вывода через &resources.
Также есть параметр &where для любой фильтрации по ресурсам.

В общем, на больших сайтах нужно применять фантазию, а не просто использовать готовые дополнения.

**Comment by SlivaNilow** [comment]
В том то и дело что из всего дерева возвращается 5 ресурсов. фильтрация идет по шаблону.
Сама функция getChildIds возвращает все дочерние без фильтрации.

**Comment by bezumkin** [comment]
Да, в этом её суть - вернуть потомков из карты сайта.

Выбери сам все нужные ресурсы более оптимальным способом и укажи для вывода в &resources.

**Comment by SlivaNilow** [comment]
Спасибо, не подумал об этом =)
