### ISSUE TITLE
[Q] Does pdoTools &tpl work with paths above webroot?

### ISSUE THREAD

**Issue by zaigham** [modx-pro/pdoTools#230]
Example:

I have my static elements, in `elements` folder as below:

```
/var/www/core/
/var/www/public/
/var/www/elements/
```

`public` is webroot.

I am giving absolute url of tpl to pdoResources like this: 

```
&tpl=`@FILE case-study.list.tpl`
```

where `[[++elements]]` is `/var/www/elements/` and I have `[[++pdotools_elements_path]]` set to `[[++elements]]`

I get no output of template, but in `&showLog` I get the following:

```
0.0002031: Could not find element file at "/var/www/elements/case-study.list.tpl".
```

If I move things under `/var/www/public/` it starts to work fine.

Is there something I am missing, or pdoResources doesn't support this behavior?

**Comment by bezumkin** [comment]
pdoTools is able to load elements [only from MODX_BASE_PATH](https://github.com/bezumkin/pdoTools/blob/5afd06fd11991b02c92b054a0de48319e8c8c6de/core/components/pdotools/model/pdotools/pdotools.class.php#L823-L825)

**Comment by zaigham** [comment]
Is there a specific reason for this restriction?
Just want to know more about it 🙂

**Comment by bezumkin** [comment]
Otherwise any manager will be able to view **any** html, tpl and php files on server

**Comment by Realetive** [comment]
@bezumkin but if I want to exclude it? It's logical – place files into the webroot if you want to make access and move it above the webroot for hide.

**Comment by bezumkin** [comment]
Just use another component
