### ISSUE TITLE
Defined placeholders have to be uncached in order to use output modifiers

### ISSUE THREAD

**Issue by vierkantemeter** [modx-pro/pdoTools#233]
I have the same problem as this issue: https://github.com/modxcms/revolution/issues/12970 It seems to be related to pdoTools.

For example, the [[+user.photo]] call needs to be uncached, or it will not work:

```
[[!Profile? &prefix=`user.` &user=`1`]]
[[!+user.photo:isnot=``:then=`<img src="[[+user.photo]]" />`:else=`No image`]]
```

Is this behaviour as is should be? Or is this a bug?

MODX 2.5.0
pdoTools 2.6.1

**Comment by bezumkin** [comment]
Try to check this behaviour on MODX 2.5.0 without pdoTools.
