### ISSUE TITLE
pdoMenu and Media Sources

### ISSUE THREAD

**Issue by zooks** [modx-pro/pdoTools#236]
PdoMenu doesn't support Media Sources. It just outputs the name of file.
`[[pdoMenu?
  &parents=`6`
  &level=`2`
  &tplInnerRow=`@INLINE <li[[+classes]]><a href="[[+link]]" [[+attributes]]><img src="[[+image]]" alt="[[+menutitle]]"><br>[[+menutitle]]</a>[[+wrapper]]</li>`
  &includeTVs=`image`
]]`

Output:
`image.png`
instead of:
`assets/images/image.png`

**Comment by bezumkin** [comment]
Try to read about &processTVs.

**Comment by zooks** [comment]
Thanks. I think you should add this parameter to the docs.
https://docs.modx.pro/en/components/pdotools/snippets/pdomenu

**Comment by bezumkin** [comment]
I think you should read [the general options](https://docs.modx.pro/en/components/pdotools/general-settings)

**Comment by zooks** [comment]
Thanks again.
