### ISSUE TITLE
pdoSitemap urlencode

### ISSUE THREAD

**Issue by faitno** [modx-pro/pdoTools#25]
Добавьте плиз на 123 строчке:
$url=str_replace(array('%25','%2F','%3A'),array('%','/',':'),rawurlencode($url));
Для поддержки кириллистических дружественных урл.

**Comment by bezumkin** [comment]
А почему у меня и сейчас работает? http://d.pr/i/IOcy

**Comment by faitno** [comment]
Теперь и так можно -)
http://clubs.ya.ru/search/replies.xml?item_no=2943

**Comment by bezumkin** [comment]
Теперь? Новость от 20 июня 2011 года.
