### ISSUE TITLE
Наборы параметров после деинсталляции пропали

### ISSUE THREAD

**Issue by vitvayti** [modx-pro/pdoTools#28]
Произвел деинсталляцию пакета.
Установил пакет.
В Инструменты -> Наборы параметров не отображаются.

Наборы параметров были созданы для pdoMenu, pdoResources. Наборы параметров не отображаются, но работаю и отображаются в настройках сниппета (вкладка параметры).

**Comment by bezumkin** [comment]
Наборы привязаны к сниппетами, а ты их деинсталлировал.

Это механизм MODX, у меня в компоненте нигде нет работы с наборами параметров.

[Видишь, связь composite](https://github.com/modxcms/revolution/blob/f2a5626afdbba13a40363609d1f3d5866cd19c9c/core/model/schema/modx.mysql.schema.xml#L1046-L1050) - это значит, что при удалении сниппета удаляются и связанные с ним наборы параметров.

Наверное для этого у них в админке есть экспорт и импорт.

**Comment by vitvayti** [comment]
Дело в том что, параметры продолжают работать и создать параметры с таким же именем нельзя, возможно они просто не отображаются, но в базе все-равно остаются?

**Comment by bezumkin** [comment]
Ищи их в Инструменты &rarr; Наборы параметров - если они есть, то должны быть там.

Может, просто связь со сниппетом нарушилась, из-за его удаления. Id то у него сменился.

**Comment by vitvayti** [comment]
В базе данных (в таблице modx_property_set) у этих наборов параметров свойства category были со значением 0, изменил на соответствующие - отобразились.

**Comment by bezumkin** [comment]
У меня нигде в pdoTools нет работы с PropertySet - ни установки, ни удаления, ни изменения category.

Возможно это баг MODX, возможно просто какое-то неочевидное поведение, не знаю.
