### ISSUE TITLE
[3.x] Could not find legacy class 

### ISSUE THREAD

**Issue by CrazyBoy49z** [modx-pro/pdoTools#300]
Консоль запущена...
Пробуем установить пакет с подписью: pdotools-3.0.0-alpha1
Пакет найден... сейчас идёт подготовка к его установке.
Загрузка рабочего пространства пакета...
Рабочее пространство загружено, сейчас устанавливаем пакет...
Could not find legacy class MODX\Revolution\.MODX\Revolution\modNamespace after converting to MODX\Revolution\MODX\Revolution\\MODX\Revolution\modNamespace
Could not find legacy class MODX\Revolution\.MODX\Revolution\modCategory after converting to MODX\Revolution\MODX\Revolution\\MODX\Revolution\modCategory
Could not find legacy class MODX\Revolution\.MODX\Revolution\modSystemSetting after converting to MODX\Revolution\MODX\Revolution\\MODX\Revolution\modSystemSetting
Could not find legacy class MODX\Revolution\.MODX\Revolution\modSystemSetting after converting to MODX\Revolution\MODX\Revolution\\MODX\Revolution\modSystemSetting
Could not find legacy class MODX\Revolution\.MODX\Revolution\modSystemSetting after converting to MODX\Revolution\MODX\Revolution\\MODX\Revolution\modSystemSetting
Could not find legacy class MODX\Revolution\.MODX\Revolution\modSystemSetting after converting to MODX\Revolution\MODX\Revolution\\MODX\Revolution\modSystemSetting
Could not find legacy class MODX\Revolution\.MODX\Revolution\modSystemSetting after converting to MODX\Revolution\MODX\Revolution\\MODX\Revolution\modSystemSetting
Could not find legacy class MODX\Revolution\.MODX\Revolution\modSystemSetting after converting to MODX\Revolution\MODX\Revolution\\MODX\Revolution\modSystemSetting
Could not find legacy class MODX\Revolution\.MODX\Revolution\modSystemSetting after converting to MODX\Revolution\MODX\Revolution\\MODX\Revolution\modSystemSetting
Could not find legacy class MODX\Revolution\.MODX\Revolution\modSystemSetting after converting to MODX\Revolution\MODX\Revolution\\MODX\Revolution\modSystemSetting
Could not find legacy class MODX\Revolution\.MODX\Revolution\modEvent after converting to MODX\Revolution\MODX\Revolution\\MODX\Revolution\modEvent
Успешно установлен пакет pdotools-3.0.0-alpha1

**Comment by Mark-H** [comment]
This is fixed in MODX 3.0.0-alpha3.
