### ISSUE TITLE
not caching uncachable tags

### ISSUE THREAD

**Issue by Bruno17** [modx-pro/pdoTools#33]
using something like that snippet - call:

```
[[!pdoPage? 
    &parents=`0` 
    &resources=`[[*id]]` 
    &tpl=`multilang_resourceTemplate` 
    &includeTVs=`mml_pagetitle,mml_longtitle,mml_introtext,mml_content,colors` 
    &prepareTVs=`1` 
    &processTVs=`1`
        &tvPrefix=`` 
    &loadModels=`migxmultilang`
        &prepareSnippet = `mmlTranslatePdoToolsRow`
        &cache = `1`
]]
```

seems to process and cache uncachable snippets in it.

is there a way not to cache uncachable snippets and other uncachable tags?

**Comment by bezumkin** [comment]
You **enabled cache** - so what do you want?

**Comment by Bruno17** [comment]
I want to cache cachable tags `[[getSomethingOnce]]` inside my tpl - chunk, but not uncachable tags: `[[!getSomethingDynamic]]`

**Comment by bezumkin** [comment]
I do not know how to do it.

**Comment by Bruno17** [comment]
ok, for now, I name them `[[!!getSomethingDynamic]]`

and do:

```
        $data = str_replace('[[!!','[[!',$data);
    $pdoPage->pdoTools->setCache($data, $scriptProperties);
```

**Comment by bezumkin** [comment]
You specify placeholder in chunk and do not want snippet to process it? You to leave it for parser?

Do you understand, that snippet will try to parse every `[[!!getSomethingDynamic]]` for 10 times?
<a rel="fancybox" href="http://st.bezumkin.ru/files/0/1/a/01ad2d856bfd9c311f929aaad1000c76.png"><img src="http://st.bezumkin.ru/files/0/1/a/01ad2d856bfd9c311f929aaad1000c76s.jpg" class="fancybox thumbnail center"></a>

I think, you need to disable cache at all - this can be faster than processing of non existing tag in snippet.

Anyway, if you want something dynamic - don`t use cache. Much better is to optimize your queries or logic.

**Comment by Bruno17** [comment]
uncachable tags should never be processed before any caching happens.
This is why they are called 'uncachable'.

**Comment by Bruno17** [comment]
of course I can use also any tag, which modx doesn't try to parse for example:

`[![!getSomethingDynamic]]` and replace that one after processing and before caching, if there is no other way
