### ISSUE TITLE
get correct pdoFetch-class also in getObject and getCollection

### ISSUE THREAD

**Issue by Bruno17** [modx-pro/pdoTools#35]
Need to have the defined pdoFetch-class also within pdoField, which is calling pdoFetch->getObject.

Changed this lines:
https://github.com/bezumkin/pdoTools/blob/master/core/components/pdotools/model/pdotools/pdofetch.class.php#L833

and

https://github.com/bezumkin/pdoTools/blob/master/core/components/pdotools/model/pdotools/pdofetch.class.php#L901

to

```
        //$instance = new pdoFetch($this->modx, $config);

        $fqn = $this->modx->getOption('pdoFetch.class', null, 'pdotools.pdofetch', true);
        if ($pdoClass = $this->modx->loadClass($fqn, '', false, true)) {
            $instance = new $pdoClass($this->modx, $config);
        }
        else {
            @session_write_close();
            exit('Fatal error: could not load pdoTools!');
        }  
```

which seems to work.

Do you want me to make a pull-request, or is it ok to post my mod here like that?

**Comment by bezumkin** [comment]
Please, make pull-request and I will merge it.

**Comment by Bruno17** [comment]
did so, thanks!

**Comment by bezumkin** [comment]
You are welcome!
