### ISSUE TITLE
tvFilters и значения по умолчанию

### ISSUE THREAD

**Issue by bezumkin** [modx-pro/pdoTools#38]
Когда значение ТВ равно его значению по-умолчанию - оно не записывается в БД и фильтрация работает некорректно.

Нужно добавить проверку на такой случай.

**Comment by Indomian** [comment]
Закинул pull-request, в котором приделана обработка самих TV (сейчас для целей правильной обработки типов numeric). Думаю на его основе можно будет доделать данную функцию.

**Comment by ghost** [comment]
ето конкретная проблема, почему ее не фиксите?

**Comment by bezumkin** [comment]
Жду, пока ты пришлешь готовое исправление. Надоело всё самому делать.
