### ISSUE TITLE
pdoNeighbors и кавычки в tpl

### ISSUE THREAD

**Issue by Realetive** [modx-pro/pdoTools#39]
Доброго времени суток, Василий.
Если попытаться указать, например, вот так:

``` html
<div class="neighbors">
  <div class="container">
    [[pdoNeighbors?
      &tplWrapper=`@INLINE <div class="row">[[+prev:default=`<div class="class">null</div>`]][[+next:default=`<div class="class">null</div>`]][[+up]]</div>`
      &tplPrev=`@INLINE <div class="class"><a href="[[+link]]">&larr; [[+menutitle]]</a></div>`
      &tplUp=`@INLINE <div class="class">&uarr; <a href="[[+link]]">[[+menutitle]]</a></div>`
      &tplNext=`@INLINE <div class="class"><a href="[[+link]]">[[+menutitle]] &rarr;</a></div>`]]
  </div>
</div>
```

, то &tplWrapper «смутится» и попытается вывести стандартный чанк. Как я понял, дело именно в двойных/одинарных кавычках при попытке указать класс для html-тега.

**Comment by bezumkin** [comment]
В INLINE чанках не работают условия, фильтры, сниппеты и другие MODX теги.

Парсер системы сначала разбирает их, и только потом они попадут с сниппет — уже без этих тегов.
