### ISSUE TITLE
Модификаторы для pdoTools

### ISSUE THREAD

**Issue by webkostya** [modx-pro/pdoTools#40]
В pdoMenu (в остальных еще не успел посмотреть) не работают модификаторы, например если проверять на пустоту вывода результата 
[[!pdoMenu:empty='пусто']]
 то хоть запрос и пустой, но все же он выводит вот такую часть 
`<ul class=""/>`
, ну вот и получается, что данных нет, но строка все же не пустая!!!

**Comment by bezumkin** [comment]
https://github.com/bezumkin/pdoTools/issues/47
