### ISSUE TITLE
date_ago от publishedon?

### ISSUE THREAD

**Issue by manicko** [modx-pro/pdoTools#41]
Добрый день, сейчас date_ago считается от createdon и в большинстве случаев это совпадает с publishedon, поэтому никаких проблем. 

Но для блога, когда используется Tickets хорошо бы сделать доступным тег по publishedon, поскольку заметки часто вперед планируются и заводятся, а уже потом публикуются. 
Ну и с товарами точно также, они могут долго висеть в системе прежде чем их опубликуют и они станут новинками для покупателей.
Было бы круто, если бы такое ТВ было доступно и от publishedon, а может и вообще можно заменить, вроде проблем не должно быть?

**Comment by bezumkin** [comment]
1. Причем здесь pdoTools?
2. Используйте отдельный сниппет dateAgo - он выведет любую дату.

**Comment by manicko** [comment]
Да, ошибся, я про ТВ [[+date_ago]], которое появилось в getTickets
