### ISSUE TITLE
Плейсхолдер ссылки при назначении в @INLINE

### ISSUE THREAD

**Issue by akimsullec** [modx-pro/pdoTools#42]
При вот таком назначении ссылки

```
&tpl=`@INLINE<li><a href="[[~[[+id]]]]">[[+pagetitle]]</a></li>`
```

в DOM ничего не выводится.
Если то же самое назначать через чанк:

```
&tpl=`someChunk`
```

в someChunk пишем:

```
<li><a href="[[~[[+id]]]]">[[+pagetitle]]</a></li>
```

, то всё работает корректно.

**Comment by bezumkin** [comment]
http://docs.modx.pro/components/pdotools/general-parameters
