### ISSUE TITLE
Parser Improvement

### ISSUE THREAD

**Issue by FuzzicalLogic** [modx-pro/pdoTools#43]
I've found myself in situations wanting to know the value of the field of a MODX Object without having to invoke a simple query Snippet. For instance: Sometimes I'd like to get the templatename of a Template by its ID. Right now, I'm solving this with Custom Output Modifiers, but it might be fairly easy to do so with the pdoParser.

**Comment by bezumkin** [comment]
I think, we must use snippet for this, not parser.

For example:

```
$pdo = $modx->getService('pdoFetch');
$template = $pdo->getArray('modTemplate', 1);
return $template['templatename'];
```
