### ISSUE TITLE
MODx permissions

### ISSUE THREAD

**Issue by paulbohman** [modx-pro/pdoTools#45]
In my tests, pdoMenu doesn't seem to obey the built-in MODx permissions. It lists pages that it shouldn't list.

**Comment by bezumkin** [comment]
```
&checkPermissions=`list`
```

**Comment by paulbohman** [comment]
Can you explain how this is designed to work? I tried this, and it didn't work. I also tried <pre>&checkPermissions=`load`</pre> and <pre>&checkPermissions=`view`</pre>, but they all still listed files that should be hidden.

**Comment by bezumkin** [comment]
Are you sure, that you configured security policies correctly? If you checking as admin - you will always see all resources.

Here is [checkPermissions method](https://github.com/bezumkin/pdoTools/blob/7c97b0bde6beb38977a8a940eef7f1bb536bdcc2/core/components/pdotools/model/pdotools/pdotools.class.php#L774-L801) and it works perfect for me.

Try to verify your permissions by Wayfinder.

**Comment by paulbohman** [comment]
Ok. Wayfinder checks permissions by default, but with pdoMenu I have to tell it to check permissions. It's different than I expected, but it works. Thanks again.
