### ISSUE TITLE
Парсер не обрабатывает вложенные сниппеты

### ISSUE THREAD

**Issue by Bournwog** [modx-pro/pdoTools#48]
Например в таком коде не будет обработан UltimateParent

```
[[pdoMenu? 
    &parents=`[[!UltimateParent?&id=`[[*id]]` &topLevel=`3`]]`
    &level=`3` 
    &parentClass=`parent`
    &scheme=`full`
]]
```

**Comment by bezumkin** [comment]
1. pdoParser не обрабатывает сниппеты, он передаёт их в modParser.
2. Эта конструкция в нём не работает: оба сниппеты должны быть вызваны или кэшированными, или нет.
