### ISSUE TITLE
custom sort option

### ISSUE THREAD

**Issue by paulbohman** [modx-pro/pdoTools#49]
As I'm working with pdoMenu, I'm noticing that the &resources parameter seems to sort by ID, even if I put the ids in a different order. Here's my call:

[[pdoMenu? &parents=`0` &resources=`99,748,443,1086` &ignoreHidden=`1` &permissions=`list`]]

The output order is 99,443,748,1086. Is there a way that I can preserve the original order (99,748,443,1086)?

**Comment by bezumkin** [comment]
Just specify &sortby=``

**Comment by paulbohman** [comment]
That may work if I am sorting by a field, but it does not work if I need to sort them in the exact order that I specify in my call in the snippet. How do I get them in this exact order?
99,748,443,1086
I can't sort by id. I can't sort by pagetitle. I can't sort by longtitle. What do I sort by?

**Comment by bezumkin** [comment]
You do not understand me. You need specify not empty &resources and empty &sortby.

```
[[!pdoMenu?
    &parents=`0`
    &resources=`1,2,25,68`
    &sortby=``
    &showLog=`1`
]]
```

http://yadi.sk/d/P4doJMcgK6JnF

**Comment by exside** [comment]
hm, could it be that your example works "as expected" as your resources are basically in the order they would be anyways (eg. ASC ids)? I remember that disussion: https://github.com/bezumkin/pdoTools/issues/26

where the outcome was

```
&sortby=`FIELD(modResource.id, "392,230,538,476,210,530,110,209,118,84,228,229")`
```

**Comment by paulbohman** [comment]
exside: my resources were _almost_ in the order of ascending IDs, but one of them was out of place. 
bezumkin: Yes, sortby=`` (empty value between the backticks) did work. Thank you. 

I would not have expected that to be the method though. I would have expected the default order to be the order that I specified in the &resources parameter. Wayfinder uses that order. Now that I know how it works, I can do it, but it would be more intuitive to use the order I specified without having to also specify an empty sort string.

**Comment by bezumkin** [comment]
pdoMenu already has default sort by menuindex, that is why you need to specify empty &sortby

And you can continue using more intuitive Wayfinder, if you like it.

**Comment by paulbohman** [comment]
pdoMenu is much faster than Wayfinder. I stopped using Wayfinder as soon as I found pdoMenu. I don't mean to say that I prefer Wayfinder, because I don't. Your software is better. And I agree that menuindex is the best field for the default sort order. Wayfinder does that too. In the specific instance of specifying exact IDs, though, Wayfinder will use the order I list them, without having to specify a separate parameter for the sort order. When specifying exact IDs, the IDs might be in several different containers/folders, so the menuindex is not a reliable method of sorting. Menuindex is reliable only when the items are in the same container/folder.

**Comment by bezumkin** [comment]
pdoMenu is based on pdoTools library, that has many features.

You can specify the only needed ids of resources in query, but sort them by publishedon field, or menuindex. Why I need to force your sorting decision?

The same rules works in pdoResources and other snippets - thanks to pdoTools.

**Comment by paulbohman** [comment]
In additional testing, I've discovered that pdoMenu still does not order the menu items in the exact order that I need. If I have resources at different levels in the hierarchy, even if I use sortby=``, pdoMenu seems to put all of the items at the top level first, then all of the items at the second level. So in this statement:
[[pdoMenu? &parents=`0` &resources=`1,20,2,21` &sortby=``]]
If 1 and 2 are at the top level, and 20 and 21 are at the second level, pdoMenu will display them in this order:
1,2,20,21
If I move resource 20 to the top level, then the pdoMenu will give me this order:
1,20,2,21
But I cannot get the desired order if 20 is on level 2.

**Comment by exside** [comment]
did you try

```
&sortby=`FIELD(modResource.id, "1,20,2,21")`
```

?
