### ISSUE TITLE
Добавить параметр использующий для tpl шаблон документа

### ISSUE THREAD

**Issue by victorbanev** [modx-pro/pdoTools#5]
1) В репозитории Modx помимо getResources есть сниппет renderResources

2) Что делает: 

 — всё то же самое, за одним исключением — шаблон для вывода документов задается НЕ через сниппет, а используется параметр «шаблон» самого документа.

3) Зачем нужно:

 — например можно очень легко и удобно ДЛЯ НЕОПЫТНОГО КОНТЕНТ МЕНЕДЖЕРА организовать вывод на главную страницу разнообразных по размеру и стилевому оформлению виджетов (используя дочерние страницы), по заранее подготовленным шаблонам. Клиент легко сможет менять порядок вывода виджетов через дерево документов, а стиль через параметр Шаблон каждого дочернего документа.

Может быть нетрудно добавить в параметры pdoResources что-нибудь типа: &useDocTpl=`1` ???

**Comment by AgelxNash** [comment]
Думаю в таком случае стоит пройтись по всем возможным вариантам и добавить параметры как в DocLister'e:
- шаблон из глобальных настроек CFG
- шаблон из плейсхолдера какого-то другого сниппета PLH ( _сомнительная польза, но может быть полезно в режиме fastmode = 0_)
- шаблон из content'a определенного документа DOC

Ну и для полноты картины шаблон из TV параметра определенного документа: DOCTV (один фиг switch это позволяет)

Ну и сразу тут напишу, по поводу проверки @ привязки. Думаю стоит более жестко задать [правила для регулярки](https://github.com/bezumkin/pdoTools/blob/master/core/components/pdotools/model/pdotools/pdotools.class.php#L538) без последующего [strtoupper](https://github.com/bezumkin/pdoTools/blob/master/core/components/pdotools/model/pdotools/pdotools.class.php#L545), т.к. ситуации бывают разные, а более жесткие проверки дисциплинируют. В частности вот [так](https://github.com/AgelxNash/DocLister/blob/master/core/DocLister.abstract.php#L767) сделано у меня:
<code>preg_match('/^((@[A-Z]+)[:]{0,1})(.*)/Asu', trim($name), $tmp)</code>

**Comment by bezumkin** [comment]
https://github.com/bezumkin/pdoTools/commit/976e62faf0ab3ba49beedd81cc9cfd4ed5a4e573
