### ISSUE TITLE
Использование Teleport

### ISSUE THREAD

**Issue by vbatushev** [modx-pro/pdoTools#51]
У меня нестабильное присутствие интернета, поэтому нередко сайт я делаю на локальном сервере, а потом переношу на внешний. Раньше я делал это с Vapor, однако разработчики MODX соорудили еще один инструмент, который гибче указанного Vapor — Teleport (https://github.com/modxcms/teleport).
Пакует-распаковывает — всё супер.Но есть пара моментов — это нефункционирование после инъекции сайта (в терминологии телепорта) пакетов Ace и pdoTools. И если первый лечится простым реинсталлом да и не влияет на фронтенд, то pdoTools заработал только после удаления, закачки заново, установки и "жесткой" очистки кэша. При этом, понятно, что во время всех этих операций во фронтеде не работали сниппеты, ипользующие pdoTools, и, как следствие, вместо страниц показывалось сообщение об ошибке.

**Comment by bezumkin** [comment]
Мне кажется, это нужно писать авторам Teleport.

У меня не желания разбираться в логике его работы и подгонять свое дополнение под нее.

**Comment by vbatushev** [comment]
Ну, я скорее с целью информирования написал :)
Буду переносить еще раз, покопаюсь сам, чего там не так.

**Comment by bezumkin** [comment]
Могу только предположить, что не переносятся специальные классы, которые лежат в системной директории `/core/model/modx/pdotools/`.

Или не переносятся системные настройки pdoTools, в которых указан fqn путь к ним.
