### ISSUE TITLE
Line 52 of pdomenu.class.php broken?

### ISSUE THREAD

**Issue by atmmarketing** [modx-pro/pdoTools#53]
```
if ($pdoClass = $modx->loadClass($fqn, '', false, true))
```

This will never evaluate to true, since the second parameter is empty, and $modx has no idea where to get the include file.

The above line only works when I do this:

```
if ($pdoClass = $modx->loadClass($fqn, MODX_CORE_PATH . 'components/pdotools/model/', false, true))
```

**Comment by bezumkin** [comment]
Path is not needed because specified full qualified name and pdoTools install [these classes](https://github.com/bezumkin/pdoTools/tree/master/core/model/modx/pdotools) to MODX core.

See [history of this feature](https://github.com/bezumkin/pdoTools/issues/27).

**Comment by atmmarketing** [comment]
I can see that those 2 class files were _not_ installed in core/model/modx/.

I was not aware that folder required write permission for PHP/Apache. Obviously the package did not install correctly, is there even a way to tell when it does that?

**Comment by bezumkin** [comment]
As I see - it tells

``` php
if ($pdoClass = $modx->loadClass($fqn, '', false, true)) {
    $this->pdoTools = new $pdoClass($modx, $config);
}
else {
    @session_write_close();
    exit('Fatal error: could not load pdoTools!');
}
```

You can put this files to core manually.

**Comment by atmmarketing** [comment]
Thanks so much for your help. I never would have figured out that the install was corrupted because of bad permissions in the /core/model/modx folder.

**Comment by ghost** [comment]
In what way is this a "feature"? Why would there need to be files in the core/model/modx/ directory, when all they do is include the class files from core/components/pdotools?

**Comment by bezumkin** [comment]
You can overload all methods of pdoFetch and pdoTools by specifying your own classes in system settings - and all snippets will work with the new logic. See [example](https://github.com/bezumkin/pdoTools/issues/27#issuecomment-31602321).

By the way, this improvement was made for [package](http://modx.com/extras/package/migxmultilang), that you have initiated. And now [it uses this feature for work](https://github.com/Bruno17/migxmultilang/tree/master/core/model/modx/pdotools).

Also this allows do to so:

```
$pdo = $modx->getService('pdoTools');
echo $pdo->getChunk('@INLINE <p>[[+tag]]</p>', array('tag' => 'myvar'));
```

It is very useful in custom snippets.

**Comment by ghost** [comment]
Yes, I figured this out from reading other logs. It seems to me, though, that it should be the responsibility of component developers to access pdoTools from the standard, expected location, not the responsibility of pdoTools to behave in a non-standard, unexpected way to make it easier for the component developers. Other problems with this may well appear besides the file permissions issue during installation.

**Comment by bezumkin** [comment]
This if the first such issue for long time.
Did you know many hostings, where **/core/packages** and **/core/components/** has one permissions and **/core/model** - another? 

pdoTools classes are in standard path /core/components/pdotools/model - any developer can load them from here.

But just for developers easier and better to use

```
$pdo = $modx->getService('pdoFetch');
```

It will return pdoTools class, that specified in system settings. Maybe, with migxMultiLang enhancements or another.

MODX allows to overload request and response classes, parser, filters and other critical parts of system. pdoTools does the same.

**Comment by atmmarketing** [comment]
I guess I started this when I was trying to determine exactly which MODX folders require PHP Write Permission. Whether or not these directories should have Write Permission is not for me to say, I'm just interested in knowing which ones need it for critical functions like Package Installation.

**Comment by bezumkin** [comment]
MODX package system allows to install anything in all directories. There is no restrictions for developers.

If you want, that your service will available by

```
$service = $modx->getService('service');
```

you will need to install your service in **/core/model/modx/service**

In other hand you will need to do so:

```
$service = $modx->getService('service','Service', MODX_CORE_PATH.'components/service/model/service/', $scriptProperties);
```

pdoTools is designed to facilitate the life of users and developers, so I chose the first option.

**Comment by Bruno17** [comment]
wouldn't it be possible to add the path to the system setting 
`pdoFetch.class` for example: `mmlfetch:{core_path}components/migxmultilang/model/migxmultilang/`

**Comment by ghost** [comment]
The point here is that pdoTools is installing files into a non-standard location, for no other reason than to make it easier for component developers to use getService(). The developer could use the "path" parameter in getService(), so this feature isn't really necessary. While at this time there is only the one problem with this, involving servers with carefully controlled file permissions, any unexpected, non-standard behavior is liable to cause problems at some point.

**Comment by bezumkin** [comment]
Let me decide what really necessary in my component, ok?

I don`t know any "standard locations" - MODX packages has no restrictions about it.

**Comment by atmmarketing** [comment]
In understand that Revo is a totally different beast to Evo, but we run the latter with PHP Write Permission on the **cache**, **images** and **files** folders only, so it seemed natural to run Revo locked down as tight as possible.

**Comment by Bruno17** [comment]
If we could add a path to the system-settings, developers could decide where to find the files.
May be, it's possible to select the location at installation-time, then.

**Comment by bezumkin** [comment]
[xPDO::getService()](https://github.com/modxcms/revolution/blob/886c30e881123ab026a310a170776b33ca967dc6/core/xpdo/xpdo.class.php#L1211-L1216) checks system setting and allows to specify **fqn** for loading service.

[xPDO::loadClass()](https://github.com/modxcms/revolution/blob/886c30e881123ab026a310a170776b33ca967dc6/core/xpdo/xpdo.class.php#L588) takes this **fqn** as the first parameter and searching class in core of system.

And this logic allows me to use simple

```
$pdo = $modx->getService('pdoTools');
```

In the beginning this feature was made by extensions package, but it generates an errors, because extension packages must have the model.

Then I [changed it to system settings](https://github.com/bezumkin/pdoTools/commit/28485dd75661f6b28bc734b6c636119a3d91340b). And we have the only **one issue for 6 month** about this feature.

**Comment by bezumkin** [comment]
Now you will see errors in log, but snippets will still work.

**Comment by Bruno17** [comment]
I've send a pull - request, where you can set the path with the system-setting
https://github.com/Bruno17/pdoTools/commit/1c5efbe4a49e6c7364a708d2f3530d3d634fedae

**Comment by ghost** [comment]
So the pdotools files installed in core/model/modx/ are no longer necessary?

**Comment by Bruno17** [comment]
as far as I can tell,
they are not longer necessary and you can put custom - pdofetch - classes to  
core/components/pdotools/model/

but modx does log an error each time you call that class.

with this pull, which wasn't accepted, you could define a custom-path to the fetch - class:
https://github.com/bezumkin/pdoTools/pull/54

**Comment by atmmarketing** [comment]
Thankyou, bezumkin.
