### ISSUE TITLE
Добавление плейсхолдера количества потомков

### ISSUE THREAD

**Issue by nartzis** [modx-pro/pdoTools#57]
Если здесь 
https://github.com/bezumkin/pdoTools/blob/master/core/components/pdotools/model/pdotools/pdomenu.class.php

138-140 строки

``` php
else {
    $row['children'] = 0;
}
```

заменить на 

``` php
if (!empty($row['children'])){
    $row['children'] = count($row['children']);
} else {
    $row['children'] = 0;
}
```

то мы в шаблоне меню сможем использовать плейсхолдер количества потомков у всех элементов, а не только у активного. 
На мой взгляд, это будет удобно для решения многих практических задач.

**Comment by nartzis** [comment]
Обнаружил глюк в таком решении
Для родительских документов данный плейсхолдер отображался неверно

Поэтому вернул всё как было и на 124 строчку вставил следующие строки

``` php
if (!empty($row['children'])){
    $row['childrencount'] = count($row['children']);
} else {
    $row['childrencount'] = 0;
}
```

и теперь в чанках использую плейсхолдер [[+childrencount]]

**Comment by bezumkin** [comment]
Недостаток этого плейсхолдера в том, что он показывает реальное количество выбранных документов.

Если установлен &level и документы в контейнере не были выбраны, то и плейсхолдер покажет 0.

Поэтому я добавил новый параметр &childrenCount, который выводит всех опубликованных и неудалённых потомков ресурса.
