### ISSUE TITLE
Аналог renderResources

### ISSUE THREAD

**Issue by StKrezz** [modx-pro/pdoTools#63]
В официальном репозитории есть сниппет renderResources, который отображает выборку страниц использую указанный в настройках страницы шаблон. Весьма полезная вещь временами.

**Comment by bezumkin** [comment]
Давно есть https://github.com/bezumkin/pdoTools/issues/5

**Comment by StKrezz** [comment]
Да, чуть позже увидел и закрыл. Извиняюсь за беспокойство.

2014-05-29 11:27 GMT+06:00 Vasily Naumkin notifications@github.com:
