### ISSUE TITLE
Console log output

### ISSUE THREAD

**Issue by ghost** [modx-pro/pdoTools#64]
I have a pdoResources call that gets triggered at OnSiteRefresh. It's logging this to the console:

```
SELECT SQL_CALC_FOUND_ROWS `modResource`.`id`, `modResource`.`type`, `modResource`.`contentType`, `modResource`.`pagetitle`, `modResource`.`longtitle`, `modResource`.`description`, `modResource`.`alias`, `modResource`.`link_attributes`, `modResource`.`published`, `modResource`.`pub_date`, `modResource`.`unpub_date`, `modResource`.`parent`, `modResource`.`isfolder`, `modResource`.`introtext`, `modResource`.`content`, `modResource`.`richtext`, `modResource`.`template`, `modResource`.`menuindex`, `modResource`.`searchable`, `modResource`.`cacheable`, `modResource`.`createdby`, `modResource`.`createdon`, `modResource`.`editedby`, `modResource`.`editedon`, `modResource`.`deleted`, `modResource`.`deletedon`, `modResource`.`deletedby`, `modResource`.`publishedon`, `modResource`.`publishedby`, `modResource`.`menutitle`, `modResource`.`donthit`, `modResource`.`privateweb`, `modResource`.`privatemgr`, `modResource`.`content_dispo`, `modResource`.`hidemenu`, `modResource`.`class_key`, `modResource`.`context_key`, `modResource`.`content_type`, `modResource`.`uri`, `modResource`.`uri_override`, `modResource`.`hide_children_in_tree`, `modResource`.`show_in_tree`, `modResource`.`properties` FROM `modx_site_content` AS `modResource` WHERE ( `modResource`.`published` = :0 AND `modResource`.`deleted` = :1 AND `modResource`.`context_key` = :2 ) ORDER BY modResource.publishedon DESC LIMIT 10 Array ( [/:0\b/] => 1 [/:1\b/] => 0 [/:2\b/] => 'stylesheet' )
```

Any idea where this is coming from, and how it can be stopped?

**Comment by bezumkin** [comment]
How do you call pdoResources?

If plugin returns something - it will be in the system console. By default plugins returns nothing.

**Comment by ghost** [comment]
I already tried that &showLog property.

I am using a mashup of cssSweet and RO.IDEs. I have a context "stylesheet" and the resources in that context contain blocks of CSS directives. cssSweet uses a chunk to minimize CSS code and write it to a file. My cssSweet chunk has a getResources call to load the content of all of the "stylesheet" resources so that cssSweet can minimize it and write it to the file. cssSweet logs a success message like this

```
Success! Custom CSS saved to file "/xxxx/xxxx/www/assets/theme/css/style.css"
```

The console log message I posted above comes just before the cssSweet message, and is obviously coming from the pdoResources snippet. It's not a real problem, but it looks like there is a $modx->log() function call somewhere that isn't controlled by the logging property.

**Comment by bezumkin** [comment]
<blockquote> but it looks like there is a $modx->log() function call somewhere</blockquote>

I don`t think so. 

There is no log level and timestamp in your message.

**Comment by ghost** [comment]
That's not from the Reports -> Error Log. It's from the console when using Site -> Clear Cache. That triggers the OnSiteRefresh event. The cssSweet plugin also uses $modx->log() to generate its message, and there is no log level or timestamp.

**Comment by bezumkin** [comment]
I think it is not a bug of pdoTools.

I think it is a feature of your particular case =)
