### ISSUE TITLE
Like to sort by first by TV and then secondary sort is random order 

### ISSUE THREAD

**Issue by apathyuk** [modx-pro/pdoTools#67]
Hello, using pdoResources, I would like to sort primarily by a TV and then have a random secondary sort.  Is there a way to do this?

I would like to be able to run:

[[!pdoResources? &depth=`1` &includeContent=`1` &includeTVs=`installer_level`
    &processTVs=`0` &sortby=`{"installer_level":"ASC","pagetitle":"RAND"}`
]]

How can I do it?

Thanks

James

**Comment by bezumkin** [comment]
It is impossible in pdoResources because of SQL can`t do such sorting without nested queries.

**Comment by exside** [comment]
I guess you could just fetch the collection sorted by tv and then randomize the collection via php's native shuffle($yourCollection) function...but I guess you would have to modify pdoResources a bit, maybe with an additional $scriptProperty &shuffle=`1` or something like this...
