### ISSUE TITLE
Логика обработки параметра where

### ISSUE THREAD

**Issue by Indomian** [modx-pro/pdoTools#68]
Уже второй раз сталкиваюсь с непонятным поведением параметра where в прикладных сниппетах pdoTools. В прошлый раз в pdoNeighbors (#65), а теперь в pdoMenu. Почему при использовании параметра where фильтруется базовый объект сниппета (обычно это базовый ресурс), например родитель объекта в pdoNeighbors (хотя зачем его фильтровать не ясно) или в случае меню - текущий загруженный ресурс. pdoMenu не может получить список родителей текущего ресурса, если в вызове сниппета указан where, который не позволяет выбрать текущий ресурс. Из-за этого при верной структуре каталога ресурсов пункты меню не могут стать активными.

**Comment by bezumkin** [comment]
pdoTools выбирает все нужные ресурсы **за один запрос** - это его центральная идея.

На уровне базы данных нет никаких родителей или потомков - одни строчки с данными. Родителями и потомками они становятся уже внутри MODX, при обработке выбранного, но это происходит после применения параметра where.

Если иметь это в виду - то всё становится логично.

**Comment by Indomian** [comment]
Идея то ясна, но поведение сниппетов может быть неверным относительно логики сниппета. Сама идея выбирать всё в один запрос - классная, но не всегда она возможна. Может быть разделить всё-таки pdoTools (pdoFetch) как основу, а уже сниппеты делать чуть-чуть по тяжелее по необходимости и добавлять в них требуемые дополнительные запросы, чтобы они верно функционировали?

**Comment by bezumkin** [comment]
Насколько я вижу, текущая логика работы не устраивает ровно одного человека - тебя.

Пиши свои сниппеты, чтобы всё работало как надо. pdoTools это прекрасно позволяет.

**Comment by Indomian** [comment]
Я думаю никто просто не обращал внимания на эту проблему, т.к. у него она не возникала. А по поводу своих сниппетов - у меня форк есть под эти нужды. Думал просто это актуально. Вопрос то не ради спора хорошо/плохо, а скорее ради решения проблемы, мало-ли у кого она была.

**Comment by bezumkin** [comment]
> Я думаю никто просто не обращал внимания на эту проблему, т.к. у него она не возникала

О чем  и речь. Выходит, нет никакой проблемы, и ты просишь внести правки лично для твоих нужд, которые неизвестно как отразятся на других пользователях.

У pdoTools уже очень много пользователей, которые обновляют пакет неглядя, и любое изменение логики работы сниппетов может просто сломать людям сайт, а меня загрузить на неделю ответами на вопросы "ну почему раньше работало хорошо, а теперь сломалось?!?!?!".

Будут еще подобные вопросы - будем решать. Но пока их нет, уже почти за год работы.
