### ISSUE TITLE
pdoResource &resources = no output ?

### ISSUE THREAD

**Issue by em-piguet** [modx-pro/pdoTools#70]
I try to 

```
[[!getResources?
    &resources=`1682`
    &parents=`-1`
    &tpl=`@INLINE <li>[[+pagetitle]]</li>`
  ]]
```

And this work ok. 
then i try to :

```
 [[!pdoResources?
    &resources=`1682`
    &parents=`-1`
    &tpl=`@INLINE <li>[[+pagetitle]]</li>`
 ]]
```

But this doesn't output anything?! Is this normal ?

**Comment by bezumkin** [comment]
Do you know, that pdoResources **is not** getResources?

```
&parents=`-1`
```

It means that you want to exclude parent with id = 1 and all its children from the selection.

If you want to select through all parents you need to specify

```
&parents=`0`
```

Please, use in next time

```
&showLog=`1`
```

And you will know how exactly parameters works. [Russian docs are here](http://docs.modx.pro/components/pdotools/snippets/pdoresources).

**Comment by em-piguet** [comment]
My bad, i though quite all getresources param were ok in pdoresources as well.
using 

```
&parents=`0`
```

works in this case ! Thank you !

**Comment by bezumkin** [comment]
pdoResources can much more than getResources, therefore, some parameters are works different.
