### ISSUE TITLE
pdoResources сортировка

### ISSUE THREAD

**Issue by ghost** [modx-pro/pdoTools#73]
есть следующий, вероятно баг

у pdoResources есть фича - брать default value из tv если у ресурса нет значения в базе(т.е. например ни один элемент tv селекта не выбран, но есть def. val.), НО когда идет сортировка по TV элементы с таким подхваченным значением не участвуют в сортировке и выводятся перед отсортированными елементами.

и второе, если указать &sortby=`someIncludedTv` - сортировка, которая в доке по умолчанию ASC становится DESC почему то(в Show Log такое поведение в  where увидел).

**Comment by bezumkin** [comment]
Это, скорее, фича.

pdoTools работает напрямую с БД - отсюда скорость и возможности. Ты сам заметил, что "если у ресурса нет значения в базе", то "элементы с таким подхваченным значением не участвуют в сортировке".

Так что, всё верно. Если бы дефолтные значения ТВ писались в базу, всё работало бы сразу, а так нужно изобретать какой-то велосипед и задача под него [давно висит](https://github.com/bezumkin/pdoTools/issues/38).
