### ISSUE TITLE
Шаблон для уровня вложености

### ISSUE THREAD

**Issue by siegss** [modx-pro/pdoTools#76]
Неплохо бы иметь возможность определять обпределенный шаблон в зависимости от уровня вложенности (не класс от уровня, а именно шаблон для пункта меню)

**Comment by bezumkin** [comment]
По моему, вопросы оформления уровня меню нужно решать через CSS.

Для этого есть плейхолдер [[+level]], который позволяет делать в чанках так:

```
<div class="level-[[+level]]">
```
