### ISSUE TITLE
Работа pdoMenu

### ISSUE THREAD

**Issue by Bournwog** [modx-pro/pdoTools#80]
Столкнулся с расширенным меню и понял что как-то не так работает, или я идиот)
Структура меню

```
web
|-Главная
|+О компании
|+Каталог
|+Новости
|+Отзывы
|+Публикации
```

Суть в следующем, есть меню главное оно выводится из корня все пункты, что видны (Главная, О компании, Каталог) с подпунктами (level=2), остальные скрыты из меню, есть второстепенно меню (допустим Новости и Отзывы), в которое надо вывести 2 пункта из корня сайта которые скрыты, но эти пункты должны быть еще с дочерними элементами (опять же level=2) и как это сделать без where - что-то ума не приложу, а вообще можно это ли сделать?

P.S. то что помечено плюсом в меню имеет дочерние элементы

**Comment by Bournwog** [comment]
Попробуй &displayStart и &tplStart, и впредь читай мануал перед тем как задать вопрос.

**Comment by Bournwog** [comment]
Большое спасибо! Работает как надо!

**Comment by bezumkin** [comment]
Ха-ха!
