### ISSUE TITLE
pdoMenue

### ISSUE THREAD

**Issue by MacConin** [modx-pro/pdoTools#84]
using pdoMenue and a tpl like:
`
<li[[+classes]]>
 <a href="[[+link]]" title="[[+pagetitle]]" [[+attributes]]>
 [[+menutitle]]
 </a>[[+wrapper]]
</li>
`

renders the active row like
`
... title="<strong>anything</strong>" ...
`

**Comment by bezumkin** [comment]
There is [no word "strong"](https://github.com/bezumkin/pdoTools/search?utf8=%E2%9C%93&q=strong) in pdoTools sources.
