### ISSUE TITLE
проблема с использованием шаблонизатора

### ISSUE THREAD

**Issue by Setest** [modx-pro/pdoTools#88]
Привет. На сайте используется шаблонизатор, открывающиеся и закрывающиеся скобки у него {{ и }}. В данном случае выполняется он после парсера modx? т.е. после того как выполнятся все сниппеты,  заменятся плейсхолдеры и т.д. В методе **_loadChunk** есть замена: 

``` php
$content = str_replace(array('{{','}}'), array('[[',']]'), $content);
```

Очевидно, что если я буду использовать в чанках шаблонизатор, то понятно что произойдет. Помниться это должны быть фишка... я думаю лучше это вынести как доп опцию в свойства.

**Comment by bezumkin** [comment]
Соболезную.
