### ISSUE TITLE
шаблоны

### ISSUE THREAD

**Issue by Setest** [modx-pro/pdoTools#89]
Предлагаю вынести tplPath также в глобальные настройки, а то не красиво выглядит если прописывать его в каждом сниппете. Проще сразу как префикс к tpl с "@FILE:" его добавлять. Какое то масло-масляное получается.

**Comment by Indomian** [comment]
Эээ, а какже группы параметров...

**Comment by Indomian** [comment]
Может стоит научиться ими пользоваться? Или сразу параметры сниппета по умолчанию...

**Comment by Setest** [comment]
группы... не тоже не красиво, а вот параметры сниппета, да чет подзабыл что там можно ковырнуть. А можно и как я предложил.

**Comment by bezumkin** [comment]
То есть, удобнее прописывать путь в имени **каждого чанка**, нежели задать **одну** директорию при вызове сниппета? Например, у mFilter2 легко может быть и 20 и 30 чанков.

К тому же, файловые чанки можно сразу хранить в стандартной директории - /assets/elements/chunks и ничего не прописывать.

В общем, профит не ясен, закрываю.
