### ISSUE TITLE
tvFilters problem

### ISSUE THREAD

**Issue by pawelmil** [modx-pro/pdoTools#90]
Hi,
- I get blank output when I use pdoResources and tvFilters+default TV value
- I have a problem with pdoPage and tvFilters: 
  *when I use [[pdoResources my pagination disappears ater first click
- when I use [[!pdoResources I get blank output

**Comment by bezumkin** [comment]
Do not use pdoResources.

**Comment by pawelmil** [comment]
ok, thanks
