### ISSUE TITLE
Resource Groups Not Respected

### ISSUE THREAD

**Issue by crimsonpixel** [modx-pro/pdoTools#92]
Hi there, really liking this group of extras for MODX however, notice when using the pdoMenu that it doesn't seem to respect Resource Groups. I've got a couple of Resources which are part of a New Editor group and I only want these visible when the users are logged in, at the moment, it seems they are always visible.

Or is there a property that I'm missing in the pdoMenu call?

 [[!pdoMenu? &startId=`0` &hereClass=`current`  &tplOuter=`outerNavTpl` &tplInner=`innerNavTpl` &level=`2` ]]

**Comment by bezumkin** [comment]
http://docs.modx.pro/en/components/pdotools/snippets/pdomenu
You need yo use parameter &checkPermissions

```
&checkPermissions=`list`
```

**Comment by crimsonpixel** [comment]
Thanks Bezumkin for speedy response - and works a treat! Many thanks...
