### ISSUE TITLE
Problems with depth and resources parameter in pdoResources

### ISSUE THREAD

**Issue by pepebe** [modx-pro/pdoTools#94]
I'm just beginning to work with pdoTools and sofar everything went very smooth. Thanks for your work.

Today I ran into a problem:

Seems pdoResources is the handling the depth parameter a bit wrong.

This is my snippet call:

```
            [[!pdoResources?
                &parents=`14`
                &depth=`1`              
                &resources=`-15`
                &tpl=`cleanlab_widgets_startseite_services_tpl`
                &limit=`99`
            ]]
```

As far as I remember the children of the parent resource should be depth = 1, but I might be wrong on that. I'll do a checkup on this topic later today or tomorrow, if I'm wrong I'll post a very emberassed apology... 

I run pdotools-1.9.5-pl1 with experimental features.

Cheers,

pepebe

P.S. &resources actually works fine, but I can't change the title of the topic.

**Comment by bezumkin** [comment]
The `&depth` parameter effects only on `&parents`, but not on `&resources`.

See the [source code](https://github.com/bezumkin/pdoTools/blob/49374c0cb1612aa9392dad01eb0f12dc88202ada/core/components/pdotools/model/pdotools/pdofetch.class.php#L628-L644).
