### ISSUE TITLE
Notice: Undefined index

### ISSUE THREAD

**Issue by hichnicksemen** [modx-pro/pdoTools#96]
Периодически проскакивает:
Notice: Undefined index: children in pdomenu.class.php on line 140

**Comment by bezumkin** [comment]
Вроде уже исправлено https://github.com/bezumkin/pdoTools/pull/91

Версия последняя?

**Comment by hichnicksemen** [comment]
была версия 1.9.6pl, обновился до 1.9.6pl1, пока не выскакивает.
