### ISSUE TITLE
pdoResources and SimpleCart

### ISSUE THREAD

**Issue by ghost** [modx-pro/pdoTools#98]
SimpleCart uses a custom resource type, with several custom fields. The &includeContent property must be set to use these fields with getResources, which will then provide the placeholders. Even with &includeContent set, pdoResources does not provide the placeholders. Perhaps this is because when &includeContent is set, getResources uses toArray on the whole resource object, while pdoResources does not?

**Comment by bezumkin** [comment]
Yes, I think so.

You can use &leftJoin parameter for joining all needed fields manually.

**Comment by ghost** [comment]
Where is this documented? It's not in the tables in the modxpro docs. Or did you mean &select?

**Comment by bezumkin** [comment]
https://bezumkin.ru/training/course2/3006/

```
[[!pdoResources?
    &parents=`0`
    &class=`modResource`
    &loadModels=`ms2gallery`
    &leftJoin=`{
        "Image": {
            "class": "msResourceFile",
            "on": "modResource.id = Image.resource_id AND Image.parent = 0"
        },
        "Thumb": {
            "class": "msResourceFile",
            "on": "Image.id = Thumb.parent AND Thumb.path LIKE '%120x90%'"
        }
    }`
    &select=`{
        "modResource": "*",
        "Image": "Image.url as image",
        "Thumb": "Thumb.url as thumb"
    }`
    &showLog=`1`
    &sortby=`id`
    &sortdir=`ASC`
]]
```

**Comment by Jako** [comment]
This should go in the pdoTools docs as example.
